### ISSUE TITLE
Chunks Bug (common occurance, not consistent tho)

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#121]
**Describe the bug**
Sometimes after joining the proxy, some chunks will appear empty and in some cases, invisible terrain all around you. (See screenshots below) 

**To Reproduce**
1. Join Proxy
2. Look around
3. Load chunks

**Expected behavior**
Chunks load & are visible + no missing sections of chunks

**Screenshots**
[Click Here](https://imgur.com/a/CidvUxK)

**Server version**
Running Paper version git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Geyser version**
Latest Commit (master branch)

**Bedrock version**
1.14.1.4

**Additional context**
Sometimes a relog will make chunks appear as normal again, the bug is inconsistent but it should still be fixed before a stable release.

**Comment by Legit4K** [comment]
I managed to get a log this time: https://textbin.net/EZu6c3Qqcg

**Comment by RednedEpic** [comment]
Little update on this. AJ brought to my attention a couple days ago that the java chunk packet consists of a full chunk and a non-full chunk. A full chunk, as you might expect, consists of a _whole_ chunk update, while a non-full chunk update only represents a section of the chunk (basically a large multi-block update packet).

So with this being said, we are not currently handling non-full chunks, because we treat every chunk packet as a full-chunk packet. This pretty much explains this issue and hopefully soon we should have a fix.

**Comment by Legit4K** [comment]
Fixed in #156
