### ISSUE TITLE
Ability add Commands

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#1371]
**What feature do you want?**
Geyser presently has a unified method of adding sub commands to the Geyser command. However it will be useful to allow root commands to be added in a unified manner, especially for extensions, and they should support aliases etc which can gracefully fail if already bound in the platform.

**Comment by RednedEpic** [comment]
Thanks for the suggestion, however since this feature request was made we've expanded upon the Geyser command system quite a bit and it currently injects into all the platform command managers we support. Essentially this means we'd need to add support for adding arbitrary commands inside of Geyser through the extensions system which goes a bit out of the scope of the extension API.

An API has been added however that allows for custom aliases, but ultimately custom root commands is a bit out of scope. Thanks for the feature request tho!
