### ISSUE TITLE
kick on villager interaction

### ISSUE THREAD

**Issue by quartzexpressDEV** [GeyserMC/Geyser#138]
**Describe the bug**

When you try to interact(right click) with villagers, you get kicked from the server with following error message in the console: 

quartzexpress has disconnected from remote java server on address 0.0.0.0 because of io.netty.handler.codec.DecoderException: java.lang.NullPointerException: secondInput is marked non-null but is null
Bedrock user with ip: /192.168.2.112 has disconnected for reason CLOSED_BY_REMOTE_PEER

**To Reproduce**
1. Go to a village or spawn a villager
2. Right click the villager
3. See error

**Expected behavior**
No kick when interacting with villagers.

**Screenshots**

**Server version**
1.15.1 vanilla

**Geyser version**
Build #165

**Bedrock version**
1.14.1

**Additional context**

**Comment by EOT3000** [comment]
Are you using standalone, bungee, or bukkit version. Also, are you using flootgate?

**Comment by quartzexpressDEV** [comment]
i'm using the standalone version. As i dont know what floodgate is, i guess im probably not using it

**Comment by RednedEpic** [comment]
I think this is in part due to the fact that the trade packet has not yet been implemented. The issue lies in [this line](https://github.com/Steveice10/MCProtocolLib/blob/cd86de19efb0682fd78f73560a8e3131e240d1b9/src/main/java/com/github/steveice10/mc/protocol/data/game/window/VillagerTrade.java#L12) of code in MCProtocolLib. A [pending pull request](https://github.com/Steveice10/MCProtocolLib/pulls) on that repository is opening that fixes that. Once merged, this issue will be resolved.
