### ISSUE TITLE
Allow specifying custom lang overrides

### ISSUE THREAD

**Issue by haykam821** [GeyserMC/Geyser#1390]
### What feature do you want?

While vanilla `TranslatableText`s get remapped into usable text on the Bedrock side, this means custom `TranslatableText`s will only show as their translation key. Similar to lang resource packs for Java Edition clients, Geyser should provide a way to extend langs with custom translations that are provided to Bedrock Edition clients.

### Alternatives?

Sending the actual text content works, but defeats the point of lang.

**Comment by onebeastchris** [comment]
https://wiki.geysermc.org/geyser/faq/#adding-custom-geyser-translation-overrides
Isn't that possible now-ish with this?

**Comment by ISNing** [comment]
> https://wiki.geysermc.org/geyser/faq/#adding-custom-geyser-translation-overrides
> Isn't that possible now-ish with this?
> 

I think this is not for custom lang overrides in Minecraft world.

**Comment by ISNing** [comment]
And I think it can be a good idea to replace the data itself in geyser proxy according to a translate table(I think this can be an easy).And the translate table can also easily generated from resource pack for java edition.

**Comment by onebeastchris** [comment]
It is now possible to add or modify Java translation strings. Documentation can be found here: https://wiki.geysermc.org/geyser/translations/

In the future, this could be expanded to automatically parsing translations from Java edition resource packs; but since those aren't touched at the moment, that's for another time.
