### ISSUE TITLE
I use both floodgate and GeyserMC 1.16.4

### ISSUE THREAD

**Issue by hackerkitteh** [GeyserMC/Geyser#1730]
help, i use geysermc and floodgate together. Java works fine everyone can play. Bedrock edition though, when bedrock players connect they cannot open chests and boxes or do/use anything. It seems like they are visitor. But they can break and harm... confusing, how do i fix this? Im running geyserMC on a dedicated PC

**Comment by Camotoy** [comment]
Please follow the issue template; thank you!

**Comment by hackerkitteh** [comment]
but its too biggggg :(

**Comment by EasyClifton** [comment]
We can't help you if you don't provide a correctly formatted issue

**Comment by Chew** [comment]
Please fill this out, once you do, we'll re-open this. Otherwise, there isn't anything we can do to help :(

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**
Please also include the link to a dump by using `/geyser dump`
