### ISSUE TITLE
Timestamp in score class is not always updated.

### ISSUE THREAD

**Issue by konradgab** [GeyserMC/Geyser#1788]
Hello i found something strange in code.
In the score class, when using the setTeam method, change updateType to UPDATE, but do not set a timestamp. 
When the setTeam method is used there is a double state change with one timestamp - setTeam changes state to update and then setUpdateType changes state to Add.

https://github.com/GeyserMC/Geyser/blob/1a08e1104d357315d1103a7e641fc8053b4c677d/connector/src/main/java/org/geysermc/connector/scoreboard/Score.java#L75

https://github.com/GeyserMC/Geyser/blob/1a08e1104d357315d1103a7e641fc8053b4c677d/connector/src/main/java/org/geysermc/connector/scoreboard/Score.java#L82

Double status change with one timestamp- 
https://github.com/GeyserMC/Geyser/blob/1a08e1104d357315d1103a7e641fc8053b4c677d/connector/src/main/java/org/geysermc/connector/scoreboard/Objective.java#L105
https://github.com/GeyserMC/Geyser/blob/1a08e1104d357315d1103a7e641fc8053b4c677d/connector/src/main/java/org/geysermc/connector/scoreboard/Objective.java#L106

**Comment by Tim203** [comment]
There is yet another scoreboard fix in the works and I don't know everything I changed we changed in there on the top of head, but I'll keep it in mind and I'll look into your issue probably tomorrow.

**Comment by Tim203** [comment]
This is intended behaviour. `Score#setTeam(Team)` is not just called in `Objective#registerScore(String, int)`, but it's also called in the update loop. The only situation when UpdateType should be `ADD` is when the score is being added. In all other situations the UpdateType should be `UPDATE`, which is why we set the UpdateType to `UPDATE` in `Score#setTeam(Team)`.
