### ISSUE TITLE
Color Text on Signs is Shortened on Bedrock

### ISSUE THREAD

**Issue by TheMattVid** [GeyserMC/Geyser#1802]
**Describe the bug**

I make signs on Java with regular text, bold text, and color text. The signs almost always look exactly the same on Bedrock when the text is regular and bolded. For color text, a few characters are cut off on each line.

**To Reproduce**

1. Make a sign on Java with color formatting on one or multiple lines. Try varying lengths.

**Expected behavior**

The text displays the same length on Bedrock as on Java.

**Screenshots / Videos**

I have none on me, but I can provide if necessary.

**Server Version and Plugins**

Paper 1.16.4

**Geyser Dump**

Not applicable.

**Minecraft: Bedrock Edition Version**

Pocket Edition on iPhone.

**Additional Context**

N/A

**Comment by Creaous** [comment]
Same issue, can reproduce.

**Comment by Creaous** [comment]
### The sign looks like this on Java Edition:
![Java](https://i.imgur.com/2FC2vyE.png)
### The sign looks like this on Bedrock Edition:
![Java](https://i.imgur.com/b1zOEwY.png)

**Comment by Creaous** [comment]
Is this a confirmed bug?

**Comment by ayunami2000** [comment]
This bug still happens to me on the latest Geyser build (with Floodgate) (ignore the java mods, they do not affect the bug):
![image](https://user-images.githubusercontent.com/24785136/123525095-74ef1580-d69c-11eb-86f3-40719338e8bb.png)

note that hex colors are used in the java signs so that may be something to do with the issue. let me know if this needs to be under a new issue.
