### ISSUE TITLE
An Idea to fix Bungeecord Resource Packs

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#1816]
**What feature do you want?**
Geyser right now cannot switch resource packs and download them as you switch through bungeecord servers. I would like this to be specifically added, but bedrock limitations are quite silly. 

**Alternatives?**
Nothing that I have specifically tried on my own, but while I was looking on spigot I found this plugin: https://www.spigotmc.org/resources/bungee-resourcepacks.6137/

It gave me the idea to download all resource packs in the beggining of joining then switch them as you switch through a bungeeserver.

You could also possibly find a way to disconnect the geyser player and reconnect them while to download the pack, but it may be a bit slower than usual.

**Comment by Camotoy** [comment]
The latter option is what we're going to go with for Java resource packs.

As this implies Bedrock resource packs, I will leave this open.

**Comment by Tydium** [comment]
> The latter option is what we're going to go with for Java resource packs.
> 
> As this implies Bedrock resource packs, I will leave this open.

Sounds good.

**Comment by onebeastchris** [comment]
Since https://github.com/GeyserMC/Geyser/commit/903e61f1a38dd66d0bd314d8ca0d6af4cc0657db , it is now possible to send different resource packs when a client connects - e.g. this velocity/bungee plugin https://modrinth.com/plugin/geyserpacksync/ uses that to send different resource packs on different backend servers.
I am not sure whether it is planned to bring this functionality to Geyser (maybe once packs are automatically converted; who knows).

**Comment by andfont** [comment]
Is there any real solution to this problem? nothing seems to work when the client is bedrock. any ideas? greetings

**Comment by onebeastchris** [comment]
As mentioned in the comment above, using a third-party-plugin would be the only option (GeyserPackSync specifically for this example, but you can e.g. make your own). There is no way to update packs on a Bedrock client without reconnecting it, which is quite unfortunate.

I'll close this issue, since it's unlikely that this would be built into Geyser.
