### ISSUE TITLE
[Feature Request] New option in config

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1866]
**What feature do you want?**
I would like to see a new option in the configuration called “bedrock-only: (boolean) ” which only allows bedrock players to join the java server and we can pick if we want “java-tweaks: (boolean)” which disables java features for the bedrock-only option.

**Alternatives?**
none

**Comment by Camotoy** [comment]
`and we can pick if we want “java-tweaks: (boolean)” for the bedrock-only option.`

What does this specifically refer to?

**Comment by GoldenMyst** [comment]
For example: java have a shorter mining distance, if “java-tweaks” is false, bedrock can mine thru that distance and etc

**Comment by Camotoy** [comment]
Mining distance will be its own setting in the future. Everything else likely belongs with another plugin - Geyser's job is to allow Bedrock players to join a Java server, not modify the mechanics on that server. (Mining distance would be an exception simply to allow mobile players to have a better experience on the server)

This "Bedrock only" config would likely work better as another plugin since that is also modifying the server.
