### ISSUE TITLE
Glowing bedrock players can't consume food

### ISSUE THREAD

**Issue by MrGraycat** [GeyserMC/Geyser#1905]
**Describe the bug**  

Any bedrock user that is glowing isn't able to consume food anymore.
This was first discovered when using eGlow for the glow effects (using packets)
However when testing this was also the case when using for example a spectral arrow.

More testing shows this is the case for any source of the glow (as this also seems to be the case using a spectral arrow)

**To Reproduce**  

1. Install Geyser and floodgate (Optional: eGlow).
2. Get a glow effect using for example spectral arrow (or using eGlow).
3. Try to consume food

**Expected behavior**  

The player should be able to consume his food. Now it just plays the animation and cancels at the end.

**Screenshots / Videos**

https://youtu.be/l0mBR9jROKs

**Server Version and Plugins**
    Version: This server is running CraftBukkit version git-Spigot-5bde311-0bad58f (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
    Plugins: eGlow, Geyser, Floodgate

**Geyser Dump**
https://dump.geysermc.org/Td1a7Bq5ha9QeJE6zVeoq0XP2Si6gpM8

**Minecraft: Bedrock Edition Version**

Tested using windows 10 minecraft build 5131175 r/16_u2

**Additional Context**

**Comment by Camotoy** [comment]
This is the second strangest bug I've seen in my time here (the first would be Bedrock clients always dealing half a heart). 

An easy way to replicate this is `/effect give @s minecraft:glowing 60 1` and then eating golden apples, since you can always eat those.
This is not something that happens with Java-only effects - Dolphin's Grace is unaffected.

**Comment by onebeastchris** [comment]
i cannot replicate this on the latest version of Geyser, seems to have fixed itself...?

**Comment by Camotoy** [comment]
I'm assuming this issue is no longer valid - when this issue opened, we sent Bedrock entity metadata every time Java updated metadata (or we did). Now, we only send Bedrock metadata when Java updates metadata (or we do), AND there's an actual change to be applied (with glowing, there is no change applied because Bedrock doesn't support this behavior). This eating bug was caused by sending entity metadata constantly; that's no longer an issue.
If this issue reappears, please open a new issue. Thanks!
