### ISSUE TITLE
invisible graves

### ISSUE THREAD

**Issue by pranshuthegamer** [GeyserMC/Geyser#1955]
**Describe the bug**

a datapack called  'Graves' by Vanilla Tweaks makes graves when you die
but the grave doesnt show

**To Reproduce**

download the datapack
connect to the server on bedrock
mine dirt 
/kill
you should see a grave but its invisible and you only see a name

**Expected behavior**

a grave should appear
![vikingoflove](https://user-images.githubusercontent.com/61378895/108518525-a753c500-72ee-11eb-91a8-63bc57afaf98.png)

**Server Version and Plugins**

papermc 1.16.5

**Minecraft: Bedrock Edition Version**

1.16.200
**Additional Context**

**Comment by CoryBorek** [comment]
I think this relates to https://github.com/GeyserMC/Geyser/issues/1251

as it uses an invisible armor stand to render the grave.

**Comment by Camotoy** [comment]
Can we get an update if this is still an issue with the latest Geyser version?

**Comment by mgallagher** [comment]
Vanilla Tweaks Graves are still invisible for me as of 3a4b1e4

**Comment by RednedEpic** [comment]
Is this still an issue? If so, does it persist when you use the [GeyserOptionalPack](https://github.com/GeyserMC/GeyserOptionalPack)?

**Comment by Chew** [comment]
No reply from OP or others so we're going to close this due to inactivity, if you experience this issue still please let us know! Thank you for reporting.

**Comment by gazpachoking** [comment]
This is still an issue with latest version.

**Comment by Camotoy** [comment]
There may not be anything we can do about it; if armor stands have blocks on their heads, Bedrock will not render it.

**Comment by Slackluster** [comment]
Hello all! No clue if this is issue is still being followed, but I am currently experiencing the same issue.

PaperMC version: Paper 1.21.8-22-main@bf465e0 (2025-08-03T15:29:10Z) for Minecraft 1.21.8
Geyser version: Geyser-Spigot v2.8.3-SNAPSHOT
GeyserOptionalPack (Build #16 · 7/4/2025) is installed and being prompted to download by Bedrock users (I realised today I can test this myself, too)

This is regarding the Graves datapack from here: https://vanillatweaks.net/picker/datapacks/

It does show the nameplate on hovering over a very specific area, but otherwise the graves are not visible.
<img width="501" height="389" alt="Image" src="https://github.com/user-attachments/assets/65e8f08b-f795-466e-b1a1-f28f9e80eba4" />

As this likely does relate to issue #1251, it's also possible there is no fix possible for this particular issue of course.
