### ISSUE TITLE
Fishing pole remaining durability not accurate

### ISSUE THREAD

**Issue by NjlsShade** [GeyserMC/Geyser#1964]
**Describe the bug**

When using the fishing pole durability will not display any lower than around 80%

**To Reproduce**

1. Load into any survival game
2. Grab a fishing pole and use it

**Expected behavior**

Durability displayed will decrease until reaching 0

**Screenshots / Videos**

https://user-images.githubusercontent.com/15788214/108650313-e9167400-7484-11eb-95cb-5f3af0e9835c.mp4

**Server Version and Plugins**

- Running the latest Java server 1.16.5
- Issue occurs on both the latest master build (Feb 21 18:57) and the latest server-inventory build (Feb 20
23:54)

- Geyser version 1.2.0-SNAPSHOT (git-master-f480fbf)
- Java: 1.16.4 - 1.16.5

**Minecraft: Bedrock Edition Version**

Running on Linux via the mcpelauncher build here: https://github.com/ChristopherHX/linux-packaging-scripts/releases
- Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201

**Additional Context**

This has happened both when using the fishing pole on mobs and for fishing

**Comment by Camotoy** [comment]
I believe we determined this was a bug with Bedrock and not us. I'll double-check on that, though.

**Comment by JuqnDeveloper** [comment]
The bug is in bedrock, you would have to reassemble the fishing rod for it to work.

**Comment by lecatos** [comment]
I have the same problem too. I was fishing with an unbreaking 3 rod and its health seems to be at about 85% and all of the sudden it broke, I lost all of the other enchantments (lure 3, luck of the sea 3). Please fix this bug.
I think it's a geyser's bug and not bedrock because when I play on single player mode on bedrock  (no geyser involve) and I tried to reproduce it, the rod seems to behave normally.

**Comment by KalixWolf** [comment]
If anyone is interested I wrote a skript on my server to work around this issue. It just sends an actionbar when the durability gets to 20% or below.

```
on item damage:
	if item is a fishing rod:
		if damage value of item is greater than or equal to 50:
			send action bar "&cRod Durability Below 20%%!" to player
```

You would need the Skript plugin on the server for this to work.

**Comment by arlojay** [comment]
The reason why is because on bedrock edition, fishing rods have 384 durability. On Java edition, they only have 64. The server says that it only has 64 damage, so the client believes that it still has 320/384 durability left. In reality, it's just about to break since it actually has 0/64 durability left.

**Comment by lecatos** [comment]
> The reason why is because on bedrock edition, fishing rods have 384 durability. On Java edition, they only have 64. The server says that it only has 64 damage, so the client believes that it still has 320/384 durability left. In reality, it's just about to break since it actually has 0/64 durability left.

If that is so, I think we can solve this problem by modifying the durability proportionate to the actual durability.
