### ISSUE TITLE
Corrupted protocol registry in PaperMC

### ISSUE THREAD

**Issue by ylluminate** [GeyserMC/Geyser#1970]
Reported an issue to to PaperMC developers the other day: https://github.com/PaperMC/Paper/issues/5202

As you can see by [the replies](https://github.com/PaperMC/Paper/issues/5202#issuecomment-783603225) there is apparently likely a problem with Geyser corrupting the protocol registry.

Any thoughts on this? Reliable reproduction has not been accomplished as of yet...

**Comment by Camotoy** [comment]
Yes, I did see that issue. I'm going to close this issue since we don't have *proof* it's us yet.

What would be helpful is:

- When does it happen?
- Is a Bedrock player online when this happens?
- Does it happen if Geyser is not installed?

If you get more conclusive proof, I would recommend opening an issue or filling it in here. Feel free to continue the discussion and I'll get notifications for the replies.

**Comment by LichLord91** [comment]
I've seen this error about 3 times in the last few months according to my logs , unsure what caused it or how it may have affected anything but the one thing  that ylluminate and i share as far as plugins is Geyser. Hope this helps  in some way.

Geyser dump: (Of course this has changed between the months always been on paper but switched to purpur probably around janurary)
https://dump.geysermc.org/CabjLGobj66xSeroIKaexF7LlN0gxmXh

2020-12-12-1.log
https://mclo.gs/23m4tA0

2020-12-21-6.log
https://mclo.gs/ga1aVz5

2020-02-01-1.log
https://mclo.gs/peTrOSN


![image](https://user-images.githubusercontent.com/8435580/108796254-2b9b8780-753d-11eb-9de7-570a8548b21d.png)
