### ISSUE TITLE
Disable / Enable Resource Packs in game (mainly for bungeecord)

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#2005]
Right now I do understand that multiple server resource packs for per-server configurations do not exist on geyser yet. (I hope it's coming soon) However what I think should be added that is somewhat related is turning on and off the resource pack depending on which server you are in.

For example, I am in my hub and have custom 3d models and custom blocks in the form of a resource pack. I do not want those 3d models, and blocks to apply to survival other wise it will look ugly.

So maybe have in the config "Resource Pack Server toggle"
Then put in the config where to use the resource pack in "file:server" format. (Example: Gorilla.mcpack:Survival)

**Comment by EasyClifton** [comment]
I may be wrong, but from my understanding,  unfortunately, because of bedrock handles resource packs, that's not possible without some trickery with reconnecting the bedrock side to the server while the java side stays connected. This is because of how resource packs work in bedrock. The bedrock client can only accept resource packs on server join and not anytime else, while java can apply a resource packs anytime the server prompts it to. Also when you're switching servers on bungee you aren't actually reconnectubg anywhere. The bungee just tricks your client into thinking you travelled to a different dimension and back and changes the surroundings.

**Comment by Tydium** [comment]
Damn thats unfortunate

**Comment by onebeastchris** [comment]
Closing this in favor of https://github.com/GeyserMC/Geyser/issues/1816, as that is effectively the same request
