### ISSUE TITLE
You can still bedrock bridge

### ISSUE THREAD

**Issue by NotGalacticFire** [GeyserMC/Geyser#2061]
### Describe the bug

So bedrock players can still bridge by placing blocks in front of them on air while java players have to crouch and place it on the block. This gives an unfair advantage to bedrock players.

### To Reproduce

Go onto a geyser server on bedrock, go up some blocks, and then try and place blocks in front of you on air.

### Expected behaviour

When you place blocks on air it shouldn't work and should work the same as java

### Server Version and Plugins

Paper version git-Paper-418 Plugins: FInvsee, floodgate-bukkit, Geyser-Spigot, GeyserUpdater, LaggRemover, OnePlayerSleep, SkinsRestorer

### Geyser Dump

https://dump.geysermc.org/ivFg4LtFiQawbtxKUYr16TyeiqnZeci0

### Geyser Version

1.2.0-SNAPSHOT (git-master-86397ef)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
I think it's apt to have a setting in Geyser to disable this - the knowledge to do so, however, is beyond me.

**Comment by YodaLightsabr** [comment]
> I think it's apt to have a setting in Geyser to disable this - the knowledge to do so, however, is beyond me.

+1 I think that if it went one way or another, the people on the other gamemode would be upset. This should be a setting just like the above nether building.

**Comment by Stonewall0210** [comment]
Would it be easier to port this feature to Java edition?

**Comment by ExusiaiMoe** [comment]
> Would it be easier to port this feature to Java edition?

That isn't a **real fix**

**Comment by Stonewall0210** [comment]
> > Would it be easier to port this feature to Java edition?
> 
> That isn't a **real fix**

Ah, ok

**Comment by Tydium** [comment]
I was thinking about this recently. I wouldn't treat this as a "bug" since it is an bedrock feature that would pretty much be changing the whole experience for bedrock players. Necessarily this would be considered hacking on a java server (if geyser wasn't on it) so you should treat this like a hack. I would say maybe create a custom anticheat or something like that to detect whenever a bedrock player is bridging in their own way. I've seen a very few servers do this, and it turns out pretty well for them.

Completely removing bridging is kinda foolish in my opinion. As there would be no real way of doing it without some form of client change. So removing it in the form of "anti cheat" seems more reliable.

**Comment by Camotoy** [comment]
Bridging will not be removed entirely - it will simply be an option for servers that wish to remove the advantage Bedrock players have. With that being said, we understand there is a reason godbridging is in the game! So there will always be an option for it to be usable - this will *likely* be the default option.

**Comment by Camotoy** [comment]
There is now a setting to prevent players from godbridging. It is disabled by default.
