### ISSUE TITLE
I can't use the lighthouse or the stone cutter

### ISSUE THREAD

**Issue by Slendergod** [GeyserMC/Geyser#2139]
### Describe the bug

When I try to use the lighthouse or the stone cutter it just doesn't open the interface.

### To Reproduce

1. Left click a stone cutter or a lighthouse

### Expected behaviour

I was hoping I could use these items

### Server Version and Plugins

JAVA 1.16.5
BEDROCK 1.16.201

### Geyser Version

La ip Geyserconnet

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
Because you cite 1.16.201 as your current version, you probably just need to update. Please download a new build from https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/ and replace your current Geyser jar with that one. If the issue persists with the new build, please run a Geyser dump and we'll reopen the issue:

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

Thank you!
