### ISSUE TITLE
Adding Command Suggestion for Old Minecraft Java Version

### ISSUE THREAD

**Issue by Hoangviphb999** [GeyserMC/Geyser#2164]
### What feature do you want to see added?

I want to adding command suggestion for Older Version of Minecraft Java because i can't completely about filling the command, Please adding it.

Thanks!

### Are there any alternatives?

No

**Comment by RednedEpic** [comment]
Thanks for the suggestion, but unfortunately this is something that is a bit out of our scope considering how much the command protocol has changed since 1.12, and the data available on older versions is not sufficient enough for us to effectively implement this considering how the Bedrock protocol operates with commands. I would recommend updating to a later version instead.
