### ISSUE TITLE
Login from saved password on OS or from token through Minecraft site

### ISSUE THREAD

**Issue by weiw11** [GeyserMC/Geyser#2236]
### What feature do you want to see added?

We should be able to fill the login form using the saved password on the device. Or open Minecraft's website and use the token from there after logging in.

The current login form does not allow the ability to copy and paste making it really difficult and tedious to login if you have a really long password.

### Are there any alternatives?

Typing in manually, but my password is 64 characters long as it's generated with a password manager. Every time I'm connecting on my phone, I have to spend 3~ minutes typing the password.

**Comment by Camotoy** [comment]
> The current login form does not allow the ability to copy and paste making it really difficult and tedious to login if you have a really long password.

At least on PC, I'm fairly sure you can copy and paste.

Anyway, to answer your issue, the Geyser config has an option for saving usernames and passwords, which likely satisfies your issue. Otherwise, after the Microsoft migration, you will be able to log in using a web browser.

We won't be implementing any new login features for Mojang accounts.

I hope that answers/satisfies your requests, so I will close this issue, but feel free to respond if you still have concerns. Thank you.
