### ISSUE TITLE
Books without text

### ISSUE THREAD

**Issue by Minecon724** [GeyserMC/Geyser#226]
**Describe the bug**
I can't read written books (on Bedrock).

**To Reproduce**
1. Open written book.
2. Can you see the text?

**Expected behavior**
I want to read text.

**Screenshots**
![Screenshot_2020-03-20-23-13-41-543_com mojang minecraftpe](https://user-images.githubusercontent.com/39800107/77210420-4382b400-6b01-11ea-8c04-ffabb956fc58.jpg)

**Server version**
Paper/1.15.2

**Geyser version**
Jenkins

**Bedrock version**
PE 1.14.30

Sorry for bad English, I'm from Poland.

**Comment by Loganh4005** [comment]
It also wipes what is in the book, making it an invalid book tag so I would say it is trying to read the bedrock format for books and it sees it doesn't have the bedrock format so it displays a blank book and that also explains why when you give back the book it says invalid book tag because the tag was wiped so there would need to be another translator that would translate the java's NBT tag into a bedrock NBT tag and why bedrock can't write books Is because the player file sees it as and Invalid Tag so it wipes the tag

**Comment by RednedEpic** [comment]
Closed in #408.
