### ISSUE TITLE
Ability to change the Java server version

### ISSUE THREAD

**Issue by GameParrot** [GeyserMC/Geyser#2269]
### What feature do you want to see added?

I want to see an ability in the config.yml file to set the Java server version. For example, I could set it to 1.12.2 to connect to a Java server on version 1.12.2, such as 2b2t.

### Are there any alternatives?

A --java-server-version=1.xx.x command line argument that you could use to set the version of the Java server.

**Comment by Camotoy** [comment]
This won't be happening on our end - our current Java support system only works with one version, and it's not simple to support multiple. I would recommend using https://github.com/ViaVersion/VIAaaS/ as an alternative alongside Geyser, since it seems you're referring to the standalone version. Thank you!
