### ISSUE TITLE
Bug when using Caves and Cliffs datapack.

### ISSUE THREAD

**Issue by PhaisanD14** [GeyserMC/Geyser#2287]
### Describe the bug

I created a server in 1.17 to test if Geyser was compatible with the official Caves and Cliffs datapack.
The plugin did not show any error in the console, so I was hopeful that it would work. It turned out it didn't. 

Basically it doesn't let you go below height 0. 
You go down to height -1 and it automatically teleports you back to 0. Also no blocks are rendered, only entities.

### To Reproduce

1. Build the 1.17 spigot server jar with BuildTools.
2. Start the server with the world that has the datapack.
3. Add the Geyser plugin.
4. Log from Bedrock and go to height 0.

### Expected behaviour

Bedrock players being able to go below height 0 and blocks actually rendering.

### Screenshots / Videos

https://user-images.githubusercontent.com/68166436/121793231-7405b080-cbd3-11eb-97d0-26239968054d.mp4

### Server Version and Plugins

[22:59:36] [Server thread/INFO]: This server is running CraftBukkit version 3130-Spigot-66f9d3c-20d3e57 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/crITiuInXHJDPP0387O3Bz8vdtVPEo0e

### Geyser Version

1.4.0-SNAPSHOT (git-master-bae4906)

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Chew** [comment]
> Basically it doesn't let you go below height 0.

This is intended bedrock behavior since they don't support it yet.

**Comment by Camotoy** [comment]
There should indeed be a warning when a player tries to join a world with extended height. Bedrock does not support it, and we currently do not have a workaround. This is also listed in the README as something unsupported. The datapack's height will be the default in Bedrock 1.18. For now, however, the behavior is intentional, and I am closing this issue report since it is already documented as not working.
