### ISSUE TITLE
Squids don't have animation

### ISSUE THREAD

**Issue by dr03ramos** [GeyserMC/Geyser#230]
When seeing a squid on Bedrock Edition, the animation is static and the squid does not turn sideways

**Comment by RednedEpic** [comment]
> When seeing a squid on Bedrock Edition, the animation is static and the squid does not turn sideways

Please fill out the issue template.

**Comment by etgoleski** [comment]
Seeing this also

**Comment by RednedEpic** [comment]
> Seeing this also

Could you provide more information? What animation specifically are you talking about? If possible, provide a video.

**Comment by JhonaBF** [comment]
**Describe the bug**
Squid not performing its animation movement.

**To Reproduce**
Steps to reproduce the behavior:
1. Go somewhere with water
2. Look for a squid, if not, you can spawn one with an egg
3. See that it is static, just moving sideways, but not moving the tentacles, or not rotating on its vertical axis

**Expected behavior**
The squid should move its tentacles and rotate on its own vertical axis when moving.

**Video**
[Squid.zip](https://github.com/GeyserMC/Geyser/files/4372282/Squid.zip)

**Server version**
Spigot 1.15.2

**Geyser version**
Inventory branch # 9

**Bedrock version**
1.14.30

**Comment by dr03ramos** [comment]
@JhonaBF correctly described

**Comment by DoctorMacc** [comment]
If anyone would like to take a stab at this, here's what I know:

- The Squid entity's `getBedrockRotation` function should be changed to return either X Z Y or Z X Y. Both had identical results that looked better but not perfect.
- The Java ServerEntityStatusPacket has an enum for resetting squid rotation.
- In the Bedrock resource pack for squids, there is this line: `"rotation" : [ 90.0, 0.0, "variable.squid.zbodyrotation" ]`

**Comment by jackson-57** [comment]
Looks like Glow Squids are also impacted by this (#2329)
