### ISSUE TITLE
GeyserSession#confirmTeleport Int2ObjectOpenHashMap$EntryIterator - Randomly error spams console ""this.wrapped" is null"

### ISSUE THREAD

**Issue by Kruize1** [GeyserMC/Geyser#2408]
### Describe the bug

https://pastebin.com/cZxXQMth

Error randomly appears and spams console 

### To Reproduce

Not too sure what causes this. 

I was the only one on the server, Op'ed, creative mode and I was mostly AFK.

I only realized there were errors when I checked the console the next day.

### Expected behaviour

No errors

### Server Version and Plugins

This server is running Paper version git-Paper-116 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: fc47872)

### Geyser Dump

https://dump.geysermc.org/FkChRC3RQ6FyYeQEx2vujCUzz5PfATTk

### Geyser Version

1.4.1-SNAPSHOT (git-inject-7ba43d9)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

(Direct Connection Branch)

**Comment by Camotoy** [comment]
Based on the stacktrace, this bug is not related to the direct connection branch. Rather, based on the underlying issue being in a Fastutil class, we're likely modifying one of their classes concurrently without marking it as concurrent. The solution to such would be simple, but the proper fix would likely be translating Java and Bedrock packets on the same thread.
