### ISSUE TITLE
**Please join to Geyser without XboxLive Signin** 

### ISSUE THREAD

**Issue by ShootRK** [GeyserMC/Geyser#2471]
### What feature do you want to see added?

Dear develper, I have explored the issues , found a similar issue like mine.  And also I learned your altitude to the issue and your answer. But I still really hope that you can accept the issue. As I come from China. Because of some reasons as we all know（the GFW）, it's hard to connect to the Xbox Live without VPN, and in our country spread the copies of VPN is illegal. So it's a little hard for the players to join in the servers powered by Geyser. I sincerely hope that you can join to Geyser without XboxLive.
My English is poor , please excuse me.

**希望开发者理解，谢谢**

### Are there any alternatives?

auth-type: offline no working to disable join in Xbox Account

**Comment by RednedEpic** [comment]
Hi, thanks for the suggestion. Unfortunately piracy is not something we support and Xbox Live is a requirement in order to play online with Minecraft Bedrock. If Xbox Live is unable in your region, unfortunately that is out of our control and we are unable to do anything in that regard sadly.

**Comment by arkrafter** [comment]
> Hi, thanks for the suggestion. Unfortunately piracy is not something we support and Xbox Live is a requirement in order to play online with Minecraft Bedrock. If Xbox Live is unable in your region, unfortunately that is out of our control and we are unable to do anything in that regard sadly.

Xbox live is not a lecense, even if game you can swith with xbox live and not

**Comment by yri066** [comment]
I live in an area where there are disruptions of the Internet and faced with the problem that having a licensed copy of the game, when you run it without the Internet, I can not log into the Xbox account and therefore log in to the server.

**Comment by WOLFRAGE99** [comment]
I've been trying to figure out for weeks now how to disable xbox authentication, I'm surprised that this is being flagged as piracy when you have a choice to sign into an account.

**Comment by MrZomka** [comment]
> I've been trying to figure out for weeks now how to disable xbox authentication, I'm surprised that this is being flagged as piracy when you have a choice to sign into an account.

Yeah, but you can't play on online servers without an Xbox account, Minecraft prevents you from doing that :p

**Comment by teknixstuff** [comment]
How come the official bedrock server has an option to disable xbox live auth requirements?

**Comment by teknixstuff** [comment]
https://minecraft.fandom.com/wiki/Server.properties#Bedrock_Edition_3

**Comment by Tommy2678** [comment]
Can you please allow us to drop the requirement. I'm trying to have an isolated lan game with both pc and mobile players, but most of my family does not log into Xbox live on mobile. They obviously own the app from the play store or app store, but we are unable to play because there is no option to turn off this xbox verification.

**Comment by TsuZing** [comment]
> Hi, thanks for the suggestion. Unfortunately piracy is not something we support and Xbox Live is a requirement in order to play online with Minecraft Bedrock. If Xbox Live is unable in your region, unfortunately that is out of our control and we are unable to do anything in that regard sadly.

You said shows that you are also a pirate, or you have no logic. On Android, you use Google account to purchase Bedrock Edition, and credential stored in your Google account. On iOS, you use Apple account to purchase Bedrock Edition, and credential stored in your Apple account. On Windows, you do use Microsoft account to purchase Bedrock Edition, but credential stored in Microsoft Store instead of Xbox Live. You can use a Microsoft account to purchase Bedrock Edition and login to another Microsoft account that has not purchased the Bedrock Edition on Xbox Live, this is officially allowed because account that stores credential is independent of Xbox Live account on any platform.

Since third-party servers do not belong to Microsoft, and Xbox Live accounts cannot verify whether the user has actually purchased Bedrock Edition, it is rude for Microsoft to require user to login Microsoft account to join third-party servers, Microsoft just promoting Xbox Live. I hope you are a real Minecraft community developer, not someone sponsored by Microsoft.

DON'T SAY YOU DON'T SUPPORT PIRACY WHEN YOU DON'T EVEN KNOW WHAT PIRACY IS

How we join server when not login Xbox live? very simple. LAN games do not require Xbox live. You only need a forwarding to join server from LAN game.

**Comment by lll-Death-lll** [comment]
Why TF can't I play a game that I bought on another platform? Why do I need to buy it everywhere? Also, Google Play is ass and doesn't even allow me to play the game I BOUGHT. How TF is this piracy?

**Comment by ZomkaDEV** [comment]
> Why TF can't I play a game that I bought on another platform? Why do I need to buy it everywhere? Also, Google Play is ass and doesn't even allow me to play the game I BOUGHT. How TF is this piracy?

Even if you owned a license for Minecraft on Android, downloading an APK for it would still be piracy, since it’s an unauthorized copy. Piracy is the creation and consumption of unauthorized copies of software, music, movies, etc - which your scenario falls under.
