### ISSUE TITLE
Mine Cart Bug

### ISSUE THREAD

**Issue by MrRedstoneYT** [GeyserMC/Geyser#2550]
### Describe the bug

When a bedrock player in a minecart gets moved by a piston in any way, the player gets ejected out of the mine cart.

### To Reproduce

1: get in mine cart
2: push the mine cart with piston
3: you get ejected

### Expected behaviour

You get kicked out of the mine cart

### Server Version and Plugins

Server is on version 1.16.5

 Plugins (22): WorldEdit, FakePlayers, SpawnProtect, WolfyUtilities, CreateYourOwnMenus, CustomCrafting, ViaVersion, ChestsPlusPlus, floodgate, Multiverse-Core, LuckPerms, Essentials, EssentialsProtect, Multiverse-Inventories, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, BedWars, CMILib, Geyser-Spigot, EssentialsSpawn, EssentialsXMPP

geyser version is for 1.17.30

### Geyser Dump

https://dump.geysermc.org/HLRbI9cWsSOrcA5Gutw2ajdfdc4rkeDc

### Geyser Version

1.4.3-SNAPSHOT (git-master-9a87959) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11 - 1.17.30)

### Minecraft: Bedrock Edition Version

1.17.30

**Comment by mkravchenko-upchain** [comment]
Hvc. 8t

**Comment by lukeeey** [comment]
I don’t understand. You said you get ejected from the Minecart but the expected behaviour is that you get kicked out of the Minecart… but you just said that you did?

**Comment by dlee13** [comment]
They misunderstood what's supposed to be explained under expected behavior. Java edition behavior is that you can be pushed around by a piston without getting ejected from the minecart.

I can confirm I'm experiencing the issue in my server as well. The use case is automated minecart stations in which pistons process outbound carts. Java edition players are able to use my stations, but Bedrock players are unable.

**Comment by Chew** [comment]
I would think ejection out of a minecart would be client-sided if this is the case only on Bedrock and not Java. The server wouldn't eject someone solely because they're on Bedrock.

**Comment by RednedEpic** [comment]
Likely not an issue on the Geyser end.
