### ISSUE TITLE
Custom skulls distance rendering

### ISSUE THREAD

**Issue by YourRapiddeath** [GeyserMC/Geyser#2619]
### What feature do you want to see added?

We have found that there are delays for a while in worlds where multiple heads exist. Wouldn't it be a way to only render heads in a short area? Or is it possible to turn off heads for individual sub-servers or even worlds?

### Are there any alternatives?

Unfortunately we only had to switch off our heads.

**Comment by Camotoy** [comment]
Delays of what sort?

**Comment by YourRapiddeath** [comment]
It seems like the client is still downloading something after entering the server. As a result, the game does not run smoothly and the FPS drops. When the heads are switched off, it no longer occurs on and the player can play immediately. If that was your questioge war on and the player can play immediately. If that was your question.

**Comment by Tydium** [comment]
So are you saying instead of rendering all the heads in the world, make a render distance for them instead?

**Comment by YourRapiddeath** [comment]
> So are you saying instead of rendering all the heads in the world, make a render distance for them instead?

Who was the question to?

**Comment by techkrill** [comment]
If I can tag onto this, I have two players who use Geyser to connect to our server. One of them is on a low-powered phone and complained of no longer being able to visit the inner portions of the server due to framerate issues. Turning off the player heads has helped tremendously, but of course that means the other Geyser player can't see them either. I second the suggestion that it'd be great to have player heads turned on or off per player, if possible :) Thanks!

**Comment by Konicai** [comment]
Per player disabling of skull rendering already exists since eb211884de765de89291b52a5414517ed61f9e0c
