### ISSUE TITLE
Bedrock anvil keeps rejecting 

### ISSUE THREAD

**Issue by Deniedlols** [GeyserMC/Geyser#2628]
### Describe the bug

 my anvil on bedrock and i need help with this bug.

### To Reproduce

click on anvil
put netherite sword in
put enchanted book in
wont enchant how many times clicked

### Expected behaviour

i expected that it would take the enchantment but it just got rejected 

### Screenshots / Videos

https://user-images.githubusercontent.com/94211761/141605883-cc12bb44-e0da-408e-994e-56a0b7da262d.mp4

### Server Version and Plugins

1.16 - 1.17

### Geyser Version

1.17 snapshot

### Minecraft: Bedrock Edition Version

1.17.40 i think

**Comment by Chew** [comment]
I ultimately think this is related to #2515. So, to confirm, can you please replicate this exact anvil maneuver on a Java profile? It's possible that Bedrock thinks you have enough levels for it but Java (who has the final say) doesn't.

**Comment by Chew** [comment]
As the fix for the above has been merged, please upgrade your Geyser then try this again on Bedrock and let us know if you have issues.

**Comment by Deniedlols** [comment]
It Works Now I Probably Think It Was A Server Lag Issue.,

**Comment by Chew** [comment]
Cool to hear! If you continue to have issues, and you're on the latest build, let us know and we can look into this further. Thank you for the report!

**Comment by lrj1818** [comment]
Hey! Can You Gus Fix That Bug Right Now? I Found It Why It Happens If Bedrock User Has Operator And Goes Gamemode Creative Grabs A Book Its Different Than The Java Book So The Anvil Keeps Rejecting 
![image](https://user-images.githubusercontent.com/77946452/235157366-0383d687-0ba9-4298-a534-fac41d5936bc.png)
Bedrock Book Thats Taken From Bedrock Edition Creative Menu VS The Java 
![image](https://user-images.githubusercontent.com/77946452/235157445-524e4850-5e34-46d6-8b9e-0036fa4caa12.png)
