### ISSUE TITLE
Multiverse "firstspawnworld" problem

### ISSUE THREAD

**Issue by vitorgueler22** [GeyserMC/Geyser#2639]
### Describe the bug

I have basically two worlds in my server, one Lobby, and one survival (linked with nether and end). On Multiverse Core configs, I've setted "firstspawnworld" to Lobby, meaning that joining players should spawn on Lobby first, but it doesn't happen, it still spawn in normal world and there's not even a teleport to Lobby. Also, Geyser insists in spawning players in the normal world first and then teleporting to the lobby on join (with other plugins, not Multiverse), and that ends up glitching some login plugins... On Java "firstspawnworld" works fine, and completely ignores the normal worlds (like it should be).

### To Reproduce

1. Go to Multiverse Core configuration.
2. Set "firstspawnworld" to Lobby.
3. Geyser still spawns in survival world, even though I've tried setting ALL spawns (even from Minecraft itself) to the Lobby.

### Expected behaviour

Completely ignore survival worlds on server join when "firstspawnworld" is setted to somewhere else.

### Server Version and Plugins

Server: PaperMC #386

Plugins: EssentialsX, Multiverse Core, Multiverse Inventories, CoreProtect, WorldEdit, WorldGuard, AuthMe, LuckPerms, Vault, Geyser and Floodgate.

### Geyser Version

1.4.3-SNAPSHOT (git-master-581c24f)

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by Camotoy** [comment]
This is very likely not a Geyser issue. If anything this is some Floodgate conflict with a plugin, so I'd try without that first.

**Comment by vitorgueler22** [comment]
I don't have a premium account to test with Floodgate :(

**Comment by vitorgueler22** [comment]
I don't have a premium Java account to test without Floodgate :(

**Comment by lazerl0rd** [comment]
If you're looking for a lobby/hub that users always spawn to, you could instead merge https://github.com/Multiverse/Multiverse-Core/pull/2460 into a custom build of Multiverse-Core. This is because  `firstspawnworld` only affects players the first time they your server, whilst the added `joinlocation` occurs every time they log in.

If you're actually looking for `firstspawnworld`'s functionality then I can't help much (since that isn't used on my server). I can say that the above, however, works for "Geyser players" so the problem might not lie in Multiverse for you (since the implementations are similar) but rather one of the other plugins (I don't use CoreProtect, EssentialsX, and AuthMe so those are my first guess candidates).

**Comment by RednedEpic** [comment]
Likely not Geyser; closing.
