### ISSUE TITLE
Cannot Connect to Java 1.18.1 Server via Bedrock 1.18.2 On Console

### ISSUE THREAD

**Issue by PreceededMold155** [GeyserMC/Geyser#2697]
### Describe the bug

I've been playing on a server with a Partnered Streamer by the name Stingin on Twitch... We recently had to change the IP because of a DDoS Attack and as soon as the IP was changed we updated Geyser to Dev Build #963 and since then people seemingly couldn't connect from Console! including me... The only people able to connect from bedrock were using a phone or PC

### To Reproduce

To Reproduce this behavior... Connect to a Java server with GeyserMC enabled via Minecraft Bedrock on a Console and try connecting...

### Expected behaviour

The screen on the bedrock client should then say "Unable to connect to world"

### Geyser Version

Revision: 3d6dd6b8ace9f9b832fad5611dc30e2de8857049 (Dev Build #963)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by PreceededMold155** [comment]
I've already tried this. An admin for that server has been helping me fix this issue but nothing has worked... We have been trying everything for the past 36 hours and nothing has worked... I have my console configured to use BedrockConnect to connect to external servers

**Comment by PreceededMold155** [comment]
also note I was able to connect on a previous version of GeyserMC I don't know which one but it was also for 1.18

**Comment by PreceededMold155** [comment]
also note I was able to connect on a previous version of GeyserMC I don't know which one but it was also for 1.18

**Comment by Camotoy** [comment]
> as soon as the IP was changed we updated Geyser to Dev Build #963 

I would assume that the IP changing is the issue. Did you try downgrading your Geyser build?

**Comment by CyberFlameGO** [comment]
I'm getting this issue too

**Comment by Wepwawetcode** [comment]
Running into this problem as well.

**Comment by Typhus1592a** [comment]
I am receiving an issue where bedrock playerss can not join, until i restart the server. Then they are good for a while. This started happening around Christmas.

**Comment by vs084069** [comment]
> I am receiving an issue where bedrock playerss can not join, until i restart the server. Then they are good for a while. This started happening around Christmas.

Same here

**Comment by vs084069** [comment]
> I am receiving an issue where bedrock playerss can not join, until i restart the server. Then they are good for a while. This started happening around Christmas.

Can try this https://github.com/GeyserMC/Geyser/wiki/Common-Issues#stuck-on-locating-server-with-no-errors

**Comment by RashbaNor** [comment]
Well, I have the same problem. I connect to the server using the Bedrock client on my PC without the slightest problem. Unfortunately, if I run Minecraft on my Xbox console it prompts me to connect to the Xbox network. The server, PC and console are all on the same LAN.

**Comment by FrancescoJacovo** [comment]
same thing with the last version!

**Comment by jgamblain** [comment]
I have been having connection issues also. For me it started when 1.18.2 came out for PE. While connected to Java/PC server I am getting Massive slowdowns, disconnected from server for timeout, and problems connecting to the server. I've tried geyser for spigot and fabric. Building from source and getting the pre-compiled jars. Nothing looks wrong in the logs except clients vanishing, and the server not being able to keep up right after boot. I know my configs are good, and I'm not sure what to try since nothing has changed except for the very slight rev change.

**Comment by Camotoy** [comment]
The original reporter has not since responded, and no changes were made in our connection code, so it's likely a hardware issue we cannot control. If you're using a 10th or 11th gen Intel processor, see #2861. If you have another issue, then please open a new issue and give as much detail as you can. Thanks.
