### ISSUE TITLE
It is not letting me join my friend's Java Edition server on my Bedrock Edition account.

### ISSUE THREAD

**Issue by githubjuris** [GeyserMC/Geyser#2797]
### Describe the bug

This is shown when I try to join my friend who is on Java Edition. ( I am on bedrock edition )

### To Reproduce

i do not understand this step.

### Expected behaviour

I expected to be able to join them.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/98796429/151915655-b56ac94b-b46a-4fbf-8dd4-d672d948a561.png)

### Server Version and Plugins

1.18.1, has geyser mc plugin, uses the website aternos for free servers.

### Geyser Dump

ok

### Geyser Version

It is not me running it, it is my friends so I do not know

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

none

**Comment by Jens-Co** [comment]
Hello there, 
First of all I recommend that the OP/Admin makes issues, This will make things more easy for us as we need a bit more technical info like the issue template describes. 

Setting up Geyser on an Aternos server is pretty straightforward since it's fully plug&play (No configuration required).

Make sure you are using the correct IP Adress and Port.
If that still does not work tell your friend to regenerate the Folder + config.yml or reinstall Geyser.

**Comment by Konicai** [comment]
This is likely a setup issue. Please contact us on our Discord for further help with this
