### ISSUE TITLE
After setting up floodgate the uuids of bedrock players changed

### ISSUE THREAD

**Issue by justme-88** [GeyserMC/Geyser#2804]
### Describe the bug

I installed floodgate but it changed the uuids and inventories of bedrock players.

### To Reproduce

1. Install floodgate and go to config.yml of floodgate.
2. Change username-prefix: "." to username-prefix: ""
3. Restart and join the server with a bedrock account

### Expected behaviour

To mantain uuids and inventories.

### Server Version and Plugins

Pufferfish version git-Pufferfish-38 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3e75ff0 on HEAD)
Plugins: ClearLag, GeyserSkinManager, InvSeePlusPlus, MyCommand, SimpleTpa, SkinsRestorer, StackMob, WorldEdit, WorldGuard, zItemStacker

### Geyser Dump

https://dump.geysermc.org/ToYdEHa4snZvJeGbGuh5nAGOZBIS9ulM

### Geyser Version

2.0.0-SNAPSHOT (git-master-f702fb4)

### Minecraft: Bedrock Edition Version

1.18.2.03

**Comment by Camotoy** [comment]
Please send full server logs from your Pufferfish server.

**Comment by justme-88** [comment]
Here there are all the ones from this day
[logs.zip](https://github.com/GeyserMC/Geyser/files/7990202/logs.zip)

**Comment by Konicai** [comment]
This is expected behaviour - the floodgate UUID is used because its much more consistent and useful than an offline mode UUID.

If you were running online-mode and bedrock players were logging in with their JE account, then tell them to perform account linking in order to login as their JE account through floodgate: https://github.com/GeyserMC/Floodgate/wiki/Features#what-is-global-linking.

If you were running offline-mode then you'll have to find a way to do data conversion. We don't support offline-mode anyway.

**Comment by TheDiscordian** [comment]
Came across this. A bit incredulous there can't just be an offline-mode toggle to use the offline mode UUIDs, saving loads of headache when trying to set this up. The hostility to the idea is wild to me as it seems like such a simple fix...

Our usage is to have a more simple linking system. If you have same name, you get same UUID, same account. Floodgate disables this, and we need Floodgate for our anti-cheat.

**Comment by Tim203** [comment]
In a future version (Geyser & Floodgate 3.0) both Floodgate and Geyser will use the same API, making it possible for anti-cheats to detect Bedrock players without needing Floodgate. It's unlikely that Floodgate itself will ever support disabling its UUID format.
