### ISSUE TITLE
Add another dimension for -64 building

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2818]
### What feature do you want to see added?

Bedrock player can't build under -64 so you tp the player in another dimension to lets him build

### Are there any alternatives?

I don't know, but I don't think so.

**Comment by Chew** [comment]
As far as I know, this is a bedrock limitation. We were able to get around it for the nether by faking the End that lets you build higher, but there's no dimension here to save us this time.

**Comment by tbvns2** [comment]
Yes, but if you don't change the dimension like that, if you try to TP the player in another dimension when it's under -64 I think that could work.

**Comment by Camotoy** [comment]
I'm going to close this because it's likely not going to happen unless Bedrock allows flexible dimensions. It's the same reason ViaVersion hasn't implemented such a thing; if we wanted it implemented, we'd have to cache block entities, biomes, and potentially entity metadata in order to transfer them all up. And then we'd have to resend everything and ensure we changed all position tags. Thanks anyway.
