### ISSUE TITLE
Skin Restorer

### ISSUE THREAD

**Issue by TheGamingDogYT7** [GeyserMC/Geyser#2876]
### What feature do you want to see added?

Bedrock players join but as Steve or Alex can you add a skin restorer?

### Are there any alternatives?

SkinsRestorerX - You cant just restore it with this plug in you have to do 1 command and its done, But would be nice to just have the bedrock skin load in automaticlly.

**Comment by rtm516** [comment]
> Skins of Bedrock player should be visible to Java players on servers with [Floodgate 2.0](https://wiki.geysermc.org/floodgate/) installed.
> If they aren't, it's possible that the skin the player is using isn't supported (Such as Persona Skins with drastically different 3D models), or that the queue for skin uploading has grown too large (and you must simply wait).
> If you are using BungeeCord/Velocity: Installing Floodgate on the backend servers also makes it so that Bedrock player's don't have to switch backend servers for their skins to start displaying.

From discord.

**Comment by JamesTheAwesomeDude** [comment]
> If they aren't… the queue for skin uploading has grown too large (and you must simply wait).

1. Is there any way to view the queue length?
2. This issue is still present as of `floodgate-spigot-2.1.0-SNAPSHOT-64`. Should this issue be **pinned** (or at least linked-to from the wiki)?
3. Possible temporary solution: send an in-game message to Bedrock users when logging in if their skin failed, _whether_ due to an overly-long queue or to failed rendering from unsupported model elements?

**Comment by Tim203** [comment]
> Is there any way to view the queue length?

Yes, either by running `/queue` in our discord or going to `https://api.geysermc.org/v2/stats`.

> Should this issue be pinned (or at least linked-to from the wiki)?

I guess we could do that, but the queue has been shrinking slowly for the last few weeks. At the current rate the queue should be pretty much empty next month around this time. However we're planning on increasing the amount of skin uploads per minute soon, so it might be less.

> Possible temporary solution: send an in-game message to Bedrock users when logging in if their skin failed, whether due to an overly-long queue or to failed rendering from unsupported model elements?

Skins don't fail even if the queue is super long, they'll stay queued.
About the skins that do fail (mostly because of invalid geometry): I guess we could do that, but I'm not confinced that it's actually useful for the person to know whether or not their skin has been accepted. We do log a message to the console if the skin has been rejected by the skin uploader (which happens before the skin is queued).

**Comment by JamesTheAwesomeDude** [comment]
> Skins don't fail even if the queue is super long, they'll stay queued.

I see -- so with the current queue length (293k… seconds?) I've got to log in _once_ (on Bedrock) to get the skin cached, then, 4 days later, any Java clients will need to _relog_ after it's processed to see the skin?

-----

> We’re using MineSkin internally. MineSkin is running on accounts donated by the community.

Hmm, just throwing ideas out there: if the queue ever starts swelling again, I wonder how viable it'd be to reimplement MineSkin internally/standalone, allowing _server operators_ to insert their own alt account credentials to have the server process itself handle skin-signing for its own users — this'd have lower latency for everyone, not rely on donated accounts, and wouldn't put additional load on Geyser's _or_ MineSkin's servers

**Comment by Tim203** [comment]
> I see -- so with the current queue length (293k… seconds?) I've got to log in once (on Bedrock) to get the skin cached, then, 4 days later, any Java clients will need to relog after it's processed to see the skin?

You need to login with your Bedrock account, then the skin gets added to the queue (if it hasn't been uploaded already).
Once the skin has been uploaded the server will get a notification that the skin has been uploaded. After that Floodgate will try to apply the skin to the player. If Floodgate is installed on the Spigot servers then it can be applied immediately, if Floodgate is installed just on a proxy then it'll be applied on the next server the Bedrock player joins (e.g. when switching from the lobby to skyblock).

>  I wonder how viable it'd be to reimplement MineSkin internally/standalone, allowing server operators to insert their own alt account credentials to have the server process itself handle skin-signing just for its own users

I personally rather see the server owners make their accounts available to be used in MineSkin, which will also lower the queue for everyone.
