### ISSUE TITLE
Please allow bedrock players to connect to java server over the same local network.

### ISSUE THREAD

**Issue by Shadowblitz16** [GeyserMC/Geyser#2877]
### What feature do you want to see added?

I would love if I could use aternos to play with my sister behind the same router.
Right now she cannot connect to me unless I use a external server from where she is. (right now that's external from where I am)

### Are there any alternatives?

There is aternos but its laggy and most likely not close to me

**Comment by Camotoy** [comment]
Geyser supports this already; there is no difference between connecting locally and connecting over the internet. The only issue is if you're trying to connect to a Geyser instance on the same computer as Bedrock on Windows, but there's a workaround for that.

I'm closing this because it's already implemented, but feel free to leave more information below.

**Comment by Shadowblitz16** [comment]
@Camotoy I host from my linux computer and my sister plays from her switch inside.
If there is a work around can you post a tutorial on it?

She gets a `cannot connect to world` error when she tries to connect to my server on my computer.
I would really appreciate it, thanks

**Comment by Camotoy** [comment]
The Switch being unable to transfer to a local IP may be a limitation of the Switch? It's failing on my current network. But port forwarding and connecting to the port forwarded IP works for me.
