### ISSUE TITLE
Feature to add a resource pack for back-end servers

### ISSUE THREAD

**Issue by Tennessene** [GeyserMC/Geyser#2912]
### What feature do you want to see added?

I would like the feature to add a bedrock resource pack for the back-end Spigot servers. If you have a Bungeecord network, you can't do this. For example, I have a server with a lobby that goes to a minigame with a resource pack. The only to add a resource pack if you have Bungeecord is to add it to the whole server network using the packs folder in its plugin folder. I need this feature if I want bedrock support.

### Are there any alternatives?

I tried sneaking in the geyser spigot plugin in there to see if it would work, but obviously it doesn't.

**Comment by Camotoy** [comment]
Unfortunately, this is something that is hampered by the Bedrock protocol - you cannot apply a resource pack after a player has joined, unless you transfer them to the same server. 
I'm going to close this issue as-is, because unless we implement tracking players over switching connections (and then cache all world data to re-send to the player), there's not much we can do.

**Comment by Anston06** [comment]
> Unfortunately, this is something that is hampered by the Bedrock protocol - you cannot apply a resource pack after a player has joined, unless you use a transfer packet to transfer them to the same server. I'm going to close this issue as-is, because unless we implement tracking players over switching connections (and then cache all world data to re-send to the player), there's not much we can do.

well, is it possible to implement tracking players over switching connections and whatever other stuff you need to do?
