### ISSUE TITLE
Armor Stand visibility issue w/ Invisibility Tag and spawning via ModelEngine/MythicMobs

### ISSUE THREAD

**Issue by jivalon** [GeyserMC/Geyser#2988]
### Describe the bug

When summoning a custom model mob in-game via MythicMobs, the armor stands and the leather horse armor (which turns into custom models with Custom ModelData) which is attached to the head slots will be invisible only in Bedrock Edition.

When adding the invisible tag to an armor stand after executing the command `/item replace entity @e[type=armor_stand] armor.head with (item)`, only the item will disappear only in Bedrock Edition.

### To Reproduce

1. Download and Install the following plugins:
 - Geyser version 2.0.3-SNAPSHOT (git-master-3862531)
 - Floodgate Artifact `#65` Spigot 
 - ModelEngine: https://github.com/Ticxo/Model-Engine-Wiki/raw/master/demo/Model-Engine-Demo-R2.5.1.jar
 - MythicMobs: https://www.mythiccraft.io/downloads/mythicmobs/free/MythicMobs-5.0.4.jar
 - ViaVersion: https://www.spigotmc.org/resources/viaversion.19254/download?version=443043
2. Set your Server to 1.17.1 PaperSpigot (make sure to create a new world if you were previously on 1.18)
3. Restart your Server
4. Download the Demo Model for ModelEngine: https://www.patreon.com/file?h=49222891&i=7678865
5. Extract the "ModelEngine" and "MythicMobs" folders in the .rar file to your `/plugins/` directory (Click overwrite if it prompts you to)
6. Launch Minecraft: Bedrock Edition and join your server
7. Execute the commands `/meg reload models` then `/mm reload` in Console or In-Game (OP)
8. Run the command `/mm m spawn kindletronsr`

### Expected behaviour

 - All armor stands and attached held/armor items will be completely invisible.
 - All other things including titles, text, AI, sounds etc. will still be visible and work

### Screenshots / Videos

[Video (Google Drive)](https://drive.google.com/file/d/1v_CGEOc2m5nmEesJ6pHPK2Lw19UbIZOz/view?usp=sharing)

### Server Version and Plugins

Server Version:
 - PaperSpigot 1.17.1

Plugins:
 - Geyser
 - Floodgate
 - MythicMobs
 - ModelEngine
 - ViaVersion

### Geyser Dump

https://dump.geysermc.org/FNbxmaSTKxRozfw2cB61pjoAFEH3sS28

### Geyser Version

2.0.3-SNAPSHOT (git-master-3862531)

### Minecraft: Bedrock Edition Device/Version

1.18.31

**Comment by ofunny** [comment]
I did some tests with the [pack-converter script](https://github.com/Kas-tle/java2bedrock.sh/issues/new?assignees=&labels=conversion&template=pack-conversion.yml&title=%5BPack%5D%3A+) from the resource pack thread using Model Engine and  MythicMobs. And it is exactly how you wrote Kas-tle, even if the default "horse_armor" item is not visible on stands in Bedrock, the custom items will be.

Here is picture where you can see the invisible stands wearing the custom models in Java
https://resource.ofunny.world/assets/postings/me_0.png

So even if it would be nice to have a tool to visualise it in Bedrock for debugging, custom items are working.
But you have to use the GeyserOptionalPack otherwise the converted models look weird in Bedrock – not sure what the pack does in detail with armor stands but it fixes that.

However, there are other bugs related to Model Engine what cause big problems. 

1. Model Engine uses invisible armor stands to display the custom models as seen in picture me_0.png –  if custom ME mobs should fit to the surface level some of those stands have to be fully or partially below surface (see picture me_1.png in Java)
https://resource.ofunny.world/assets/postings/me_1.png 

This works well in Java but causes lightning problems in Bedrock (see picture me_2.png in Bedrock) for all stands what are not surrounded by translucent blocks. 
https://resource.ofunny.world/assets/postings/me_2.png 

2. For some reason Model Engine can not detect when a custom mob gets hit by an arm swing, sword or other tool. Projectiles however work totally fine. If you try to hit a mob in Bedrock it will not detect the hit in most cases except if you get a lucky hit on the lowest part at the bottom of the mob – so I guess something gets lost here doing swings BE<>Java since Model Engine uses a server sided hit box detection – sadly I was not able to find the reason so far.
See: https://resource.ofunny.world/assets/postings/me_3.mp4

Not sure if I gonna find a solution for it.

**Comment by ofunny** [comment]
PS not sure if I should move that into a different issue – if yes I would create on and than link #2599 and #2988 to it.

**Comment by Kas-tle** [comment]
@ofunny for point 1 I don't think there's really anything Geyser can do. That's just how the lighting engine on Bedrock works unfortunately, so the only solution here would be to make the mobs in such a way that the armor stands are not clipped... there might be some stuff you could do with the render controller for the attachable/armor stand on the material side, but this is of course outside the scope of Geyser. 

For point 2 this is likely a Geyser issue of some sort, but given that ModeEngine is closed source so we don't know what mechanism is being used to detect the hitbox, you would likely need some sort of packet capture from Java Edition to determine what is being sent by the Java client to produce the hit, and then compare that to packet capture from Bedrock.

**Comment by ofunny** [comment]
@Kas-tle **for 1:** yeah I have to learn more about the way BE packs work, I honestly did not care about them until Geyser released the mapping since I'm not a BE fan and the doc about BE packs is terrible. Not sure if light emission of the custom blocks would be a possible workaround for now. Maybe also Model Engine will support auto conversation to BE packs one day, but I doubt that atm.

**For 2:** I have the quotes of the Model Engine dev here: 
> Ticxo — Today at ... PM
> so I think whats happening here is that since meg raytrace entities using player head rotation, bedrock players with "omni-hit" has to look directly at the model to hit it since the slime mounted on you is only intractable when you look at it

and
> Ticxo — Yesterday at ... PM
> the hitbox system is subject to change because of riptide. The way it works now is by mounting a slime on you that's only intractable if you're looking at a model which is why riptide is fucky. Riptide is handled on client side, ignores team collision rules and friendly fire rules, and can even hit hitbox-less entities like marker armor stands.

So I guess is up to Ticxo (Model Engine dev) if he wants to add support for Bedrock or not – because I believe that this is a Bedrock limitation what's causing the issues for the current ME hit detection. Since there is a Riptide bug with ME as well, Tcixo has to recode the hit detection now anyway – hopefully the new implementation will be BE compatible.
