### ISSUE TITLE
bedrock players having issues with items changing.

### ISSUE THREAD

**Issue by djoveryde** [GeyserMC/Geyser#3080]
### Describe the bug

I'm currently having issues where if a bedrock player places an item it changes to something else. So stone changes to snow when placed, cobble turns to leaves. Rooms are invisible and the only fix is to exit and reload back in.
Also they are experiencing an issue where crafting something gives them buttons instead of the crafted item.

Using the latest version of geyser-spigot.

Thankyou

### To Reproduce

See the bug report on how to reproduce

### Expected behaviour

expected block should be placed instead of changing to an alternative block

### Server Version and Plugins

1.19 - #1125 - Geyser.
Latest version of Paper spigot as of 06-21-22

### Geyser Version

1.19 - #1125

### Minecraft: Bedrock Edition Device/Version

1.19.0.05 - Galaxy S22 Ultra

**Comment by Jens-Co** [comment]
Can you provide us;
* Server logs, uploaded with https://mclo.gs
* Geyser dump, use console command "geyser dump" this will give you a link that you can give to us.

I think this issue will be caused by an other plugin. What you also can do is plugin debugging; Remove few plugins at a time till problem goes away.

**Comment by djoveryde** [comment]
Latest Server Log = https://mclo.gs/VE3TV14

Geyser Dump = https://dump.geysermc.org/HuRTkVHdrDNv77ocDXFLnbQzvjxKb0CG

**Comment by Konicai** [comment]
Does this still occur?

**Comment by onebeastchris** [comment]
Closing due to no response.
