### ISSUE TITLE
Cannot make Mud on Ipad Edition

### ISSUE THREAD

**Issue by BrandonT80** [GeyserMC/Geyser#3086]
### Describe the bug

Ipad users cannot fill a water bottle and then use it on dirt to make mud. I have however tested with windows bedrock edition and it works there. If it helps, when an ipad user holds a water bottle it does not show anything in their hand.

### To Reproduce

1. Logon to a server using an ipad
2. Fill a water bottle
3. Try to use on dirt

### Expected behaviour

Water bottle used on dirt to create mud. Should take water out of bottle and leave a glass bottle and the dirt block become mud.

### Screenshots / Videos

https://youtu.be/QWp3SOt6WMk

### Server Version and Plugins

This server is running Paper version git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 5593f4e)
You are running the latest version
Previous version: git-Paper-33 (MC: 1.19)

Plugins:
https://i.gyazo.com/9156bfcc8716af5e8207e1752c747669.png

### Geyser Dump

https://dump.geysermc.org/nvBlWTXlGK0uDn7VWCii5vbYH7ODEruS

### Geyser Version

2.0.4-SNAPSHOT (git-master-6032733)

### Minecraft: Bedrock Edition Device/Version

6th Gen IPAD - Bedrock Version 1.19.2

**Comment by Reuven224** [comment]
I don't believe the problem has to do with creating mud, this is connected to another bug where if mobile players try to fill water bottles by tapping on water blocks (works fine on cauldrons), even though it looks like the bottle is full it isn't really and if you put it in a chest it will revert back to being empty. The problem here is that you probably filled the bottles this way so it didn't work because the bottles weren't actually full. If you filled them from a cauldron or obtained them in another way it would probably work, as I have successfully made mid on mobile many times (however not on iPad).

**Comment by onebeastchris** [comment]
Hey! If this issue is still occurring with the latest version of Geyser, please send a new Geyser dump by running "geyser dump" in the server console & sending the link you get here. Thanks!

I wasn't able to reproduce this with the latest geyser version + creating mud on a touch screen device.
