### ISSUE TITLE
Mobs dublicating

### ISSUE THREAD

**Issue by gaussandhisgun** [GeyserMC/Geyser#311]
**Describe the bug**

Every, like, a minute of playing, mobs create their ghost-clones. They are looking exactly like their original. If I punch a ghost-mob, the original receives damage (if it is close enough to.) I can also break and put blocks inside of ghost mobs. If the original dies, ghosts are staying here. Only reconnecting to Geyser does something about that. 

**To Reproduce**

Connect to a server (latest Inventory build, April 11th)
Go somewhere
Put/spawn a single pig
Sit down and wait

**Expected behavior**

Mobs should not create their clones. At all. Ghosts create lags and make hard to find a real mob. 

**Screenshots / Videos**

Here, on http://imgur.com/a/CHgW7QZ are screenshots of that. 

**Server Version**

Got nothing from that. Nothing at all.

**Geyser Version**

Inventory #11

**Minecraft: Bedrock Edition Version**

1.14.30.2

**Additional Context**

Geyser is running in proot on Android - using UserLAnd with Debian inside. Server: alpha.betacraft.ru (1.15 capatible). My PC friend does not get that.

**Comment by gaussandhisgun** [comment]
This also works if Geyser is running on Linux laptop.

**Comment by DoctorMacc** [comment]
Unable to replicate bug with Inventory 14 and both Paper-161 and normal Minecraft 1.15.2

**Comment by gaussandhisgun** [comment]
#367 is kinda the same

**Comment by Tomobobo710** [comment]
Using java server jar for version 1.15.2 no plugins, the Geyser.jar from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ downloaded on 4-24-2020 with a couple of bedrock clients (win10 and nintendo switch on 1.14.60) I was able to produce ghost mobs.  If a player died, the moment they hit the "respawn" button in the game the mobs that were active in their player area would freeze at the moment the button was pressed.  You could return to the spot where you died and the mobs would be there frozen in the bedrock clients, but they were unable to be interacted with.  It's possible that it was an entirely different set of ghost mobs per client based on the mobs that were in their areas when they pressed the respawn button because the locations of the ghost mobs weren't the same between the clients.  Maybe the mobs were actually despawned on the java server but this info never gets passed to the bedrock client.

**Comment by DoctorMacc** [comment]
Confirmed with Tomobobo's information - Vanilla 1.15.2.

**Comment by DoctorMacc** [comment]
It does *not* happen on Paper.
