### ISSUE TITLE
Server Disconnect

### ISSUE THREAD

**Issue by TheLastKnight14** [GeyserMC/Geyser#3160]
### Describe the bug

Players keep getting disconnected on my server 

### To Reproduce

See Above

### Expected behaviour

Players to not get disconnected

### Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/31010292/180040606-1f7739ab-b04b-4de8-8eb4-429d945380a2.png)

### Geyser Dump

https://dump.geysermc.org/RgzGvgrlXZajfOAH82BaJtjvd79JLfb7

### Geyser Version

Latest

**Comment by Konicai** [comment]
Please provide full server logs through https://mclo.gs

Please also try the following and see if this problem is resolved:

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by Konicai** [comment]
Stale and not enough information, create a new issue report with more info if you still experience this
