### ISSUE TITLE
Server log - legacy ping passthrough (MiniMOTD)

### ISSUE THREAD

**Issue by sternschnaube** [GeyserMC/Geyser#3476]
### Describe the bug

Hello, the server log: https://pastebin.com/raw/GAH6Ba9L
No crash - using Fabric 1.19.3 and the newest version (#1262).

This message comes up when I have MiniMOTD installed.
The mod: https://github.com/jpenilla/MiniMOTD

I have tried to disable "legacy-ping-passthrough" and increasing the "ping-passthrough-interval", but getting still the same log.

I can connect normally via Java - was not testing it yet with Bedrock.
But I assume this works too.

### To Reproduce

Install Geyser (#1262) and MiniMOTD (2.0.10).

### Expected behaviour

No server log.

### Geyser Version

Fabric #1262

**Comment by Camotoy** [comment]
`[Netty Server IO #3/INFO]: [STDERR]: /5.83.172.206:40900 STATUS java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2926$class_2927.method_12687()" because the return value of "net.minecraft.class_2926.method_12682()" is null` This is probably the root reason.

**Comment by sternschnaube** [comment]
Hello, I've done more testing now.
Bedrock can connect normally.
The MOTD text is working - but there are no icons showing up for Bedrock clients.
On Java - everything is normal. I was creating three test examples.

![image](https://user-images.githubusercontent.com/120551916/209574898-64cf8119-a72f-4309-a808-ef9d86fb5230.png)

**Comment by Camotoy** [comment]
Icons cannot work on Bedrock.

**Comment by sternschnaube** [comment]
Oh really? I was like that worked... 😆
Good - then there is just the server log left.

**Comment by onebeastchris** [comment]
Does the passtrough issue still occur on the latest geyser version?

**Comment by sternschnaube** [comment]
I don't use Geyser at the moment and can't test the issue.
MiniMOTD needs 1.20 update too, I think.

**Comment by Konicai** [comment]
This has been fixed in MiniMOTD. 
[getPlayers()](https://maven.fabricmc.net/docs/yarn-1.19.3+build.5/net/minecraft/server/ServerMetadata.html#getPlayers()) could return null in 1.19.3. [MiniMOTD for 1.19.3](https://github.com/jpenilla/MiniMOTD/blob/bc4d1e3cdd090142bc1b160c500ce4e27279b350/platform/fabric/src/main/java/xyz/jpenilla/minimotd/fabric/mixin/ServerStatusPacketListenerImplMixin.java#L61) did not handle it. 
Sometimes since then both server and MiniMOTD [code](https://github.com/jpenilla/MiniMOTD/blob/bc4d1e3cdd090142bc1b160c500ce4e27279b350/platform/fabric/src/main/java/xyz/jpenilla/minimotd/fabric/mixin/ServerStatusPacketListenerImplMixin.java#L61) have changed and this won't happen anymore.
