### ISSUE TITLE
Trim startup message

### ISSUE THREAD

**Issue by linsaftw** [GeyserMC/Geyser#3504]
### What feature do you want to see added?

Convert this message from this:

[19:43:41 INFO] [Geyser-BungeeCord]: ******************************************
[19:43:41 INFO] [Geyser-BungeeCord]:
[19:43:41 INFO] [Geyser-BungeeCord]: Loading Geyser version 2.1.0-SNAPSHOT (git-master-90c9d5b)
[19:43:41 INFO] [Geyser-BungeeCord]:
[19:43:41 INFO] [Geyser-BungeeCord]: ******************************************

To this:

Loading Geyser version 2.1.0-SNAPSHOT (git-master-90c9d5b)

No reason for it to take 4 extra lines of terminal.

### Are there any alternatives?

No

**Comment by Camotoy** [comment]
I brought this up internally, and the consensus is that the startup message has been like this since Geyser's conception and it's not really a big deal. My personal opinion is I'm in favor of keeping the message as some sort of show for Geyser's legacy. While I understand the message is obnoxious, I don't think we're going to change this loading text, so I'll close this issue. Further discussion is still welcome, though. Thanks.

**Comment by linsaftw** [comment]
Okay. I asked this because as a developer it makes it harder to work on my test servers when Geyser is installed as the startup message alongside the others like the spammy SkinsRestorer one just hides the exceptions sometimes and I have to scroll up to see it.

**Comment by onebeastchris** [comment]
https://www.spigotmc.org/resources/console-spam-fix.18410/
you could always hide unnecessary/unwanted console logs.. Then again, there is a purpose for Geyser saying it started etc.
