### ISSUE TITLE
Users joined called !Playpuma94

### ISSUE THREAD

**Issue by schemil053** [GeyserMC/Geyser#3533]
### Describe the bug

I have a server, and when i connect with Bedrock, there is a chance that my name is !Playpuma94. I use Geyser and floodgate.

### To Reproduce

Join on a server multiple.

### Expected behaviour

User joined called !Playpuma94

### Screenshots / Videos

![2023-02-03_19 17 08](https://user-images.githubusercontent.com/64897950/216677535-f3c4bc74-759a-4c7e-b4db-bfac30c668d9.png)

### Server Version and Plugins

Geyser 2.1.0-SNAPSHOT on Waterfall, 1.19.3 Paper

### Geyser Dump

https://dump.geysermc.org/u0rWqeeQG4GCiGjF0ERC6yp0aIfuGyXk

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Windows 10 Edition, 1.19.3

**Comment by Jens-Co** [comment]
Hello there! This is a known issue and sadly one that's out of our control. Apparently Microsoft made some changes to its authentication flow and added a bug into it. 

You can ban their uuid as a temp solution. Apart from that you will have to wait till a fix is pushed.

Thanks.

**Comment by DianFenMian** [comment]
On my server and my friend's server，This issue may have been fixed now because the server Playpuma94 was kicked out（This is followed by an advertisement for Chinese Talk，These are translated into English using Bing）
在我的服务器和我朋友的服务器,现在这个问题可能已经被修复了，因为服务器的Playpuma94被踢出了
我淀粉面就是牛逼，来我基岩版服务器玩玩，QQ群号是805812240

**Comment by Camotoy** [comment]
This appears to be resolved.
