### ISSUE TITLE
Custom guis not working in new minecraft update 

### ISSUE THREAD

**Issue by el211** [GeyserMC/Geyser#3594]
### Describe the bug

I had custom guis for battlepass and shop
all was working fine before latest minecraft update 
but after the update ui still appears but cant click on anything 

### To Reproduce

open /bp
click on the rewards or quests
Nothing opens

### Expected behaviour

i was expected  to be clickable like it was ( now its not clickable anymore)

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/86126606/222935013-72d8f1d9-f39e-4168-8f26-53e6979b6032.png)
open /bp
click on the rewards or quests
Nothing opens

### Server Version and Plugins

purpur 1.18.2
using latest geyser

### Geyser Dump

https://dump.geysermc.org/mdzn4VPwHFwvLEkzgMU1BdG2BAlN0UW3

### Geyser Version

latest 

### Minecraft: Bedrock Edition Device/Version

1.19.63

**Comment by Camotoy** [comment]
Can you describe specifically when this broke? Like 1.19.63 versus 1.19.62? Also, is there a way we can reproduce this?

**Comment by Kas-tle** [comment]
We will also need the resource pack you are using to apply the GUI.

**Comment by supersheepop** [comment]
Hello I have also a problem with this resource pack. i just downloaded and converted this pack i updated everything to the lasted version.



This is how it needs to look:
![battlepass](https://user-images.githubusercontent.com/82109425/233729580-582c16d8-d91b-4ad2-b2c2-cf2f149028c3.gif)



but on my server it shows like this:

![Minecraft 21-4-2023 22_36_24](https://user-images.githubusercontent.com/82109425/233730233-cc4e8175-83ef-4c57-b921-100269e785aa.png)
![Minecraft 21-4-2023 22_36_45](https://user-images.githubusercontent.com/82109425/233730270-bad2c2fb-f45f-4cc8-a51e-89fb86c557fa.png)
![Minecraft 21-4-2023 22_37_13](https://user-images.githubusercontent.com/82109425/233730281-912845d0-aaae-4419-9efb-d31ffb8990b8.png)


here is some info:


this is my console:
![MC Server Soft 21-4-2023 22_40_56](https://user-images.githubusercontent.com/82109425/233730715-16860dcd-27ab-4a4e-a97c-abb8029918b7.png)


this is the geyser dump:
https://dump.geysermc.org/1hPaMxLdZJtyK9ZBRvhycGIeMFkg8wf2

this are my configs(this is json):
[config - kopie.txt](https://github.com/GeyserMC/Geyser/files/11299118/config.-.kopie.txt)
[geyser_mappings - kopie.txt](https://github.com/GeyserMC/Geyser/files/11299120/geyser_mappings.-.kopie.txt)

here are my packs:


mcaddon:

[geyser_addon - kopie.txt](https://github.com/GeyserMC/Geyser/files/11299138/geyser_addon.-.kopie.txt)

mypack:

[geyser_resources - kopie.zip](https://github.com/GeyserMC/Geyser/files/11299146/geyser_resources.-.kopie.zip)
[GeyserOptionalPack - kopie.zip](https://github.com/GeyserMC/Geyser/files/11299147/GeyserOptionalPack.-.kopie.zip)

JAVA PACK:

[BattlePass UI [Resource Pack].zip](https://github.com/GeyserMC/Geyser/files/11299181/BattlePass.UI.Resource.Pack.zip)


i used this tool for my packs:
https://github.com/Kas-tle/java2bedrock.sh


i dont now what the problem is? i hope that this is enough information. if u need more just send a message i will reply as soon as posible.

**Comment by supersheepop** [comment]
here are some pictures how it looks on java edition in my server:
![Minecraft 1 19 4 - Multiplayer (3rd-party Server) 21-4-2023 23_33_14](https://user-images.githubusercontent.com/82109425/233738154-d5205d23-985f-4c52-9661-1a5d89330cc1.png)
![Minecraft 1 19 4 - Multiplayer (3rd-party Server) 21-4-2023 23_33_20](https://user-images.githubusercontent.com/82109425/233738160-4b538f5a-aff7-4ee8-9ad7-a1498e1f669c.png)
![Minecraft 1 19 4 - Multiplayer (3rd-party Server) 21-4-2023 23_33_25](https://user-images.githubusercontent.com/82109425/233738169-f3a7d197-47a8-4690-80a1-73598fa4a74e.png)

**Comment by onebeastchris** [comment]
Those would not be converted automatically, as the converter only converts items with CustomModelData & stuff based on damage predicates.
Custom UIs are possible on bedrock, but you'd need to use (unfortunately pretty much undocumented) JSON UI for it.

**Comment by supersheeppro** [comment]
I’m gona get a look on that thank you very much

**Comment by onebeastchris** [comment]
Closing due to no response from the author - to reopen, provide the info Kastle/Camotoy asked for.
