### ISSUE TITLE
Sweeping Edge Book doesn't work in the anvil.

### ISSUE THREAD

**Issue by Tyviebrock** [GeyserMC/Geyser#3661]
### Describe the bug

Sweeping edge enchanted books don't work in the second slot of an anvil. 

### To Reproduce

1.) Get sweeping edge from trading or enchanting a book
2.) Attempt to enchanted your sword with the enchanted book in an anvil

### Expected behaviour

It'll enchant your sword with no issues.

### Server Version and Plugins

Paper version git-Paper-477 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 5c78e77)

### Geyser Version

2.1.0-SNAPSHOT (git-master-0f99abc) 

### Minecraft: Bedrock Edition Device/Version

1.19.73 Nintendo Switch

### Additional Context

 Additionally if you combine sweeping edge with a different enchantment, it needs to be in the first slot.

However if try to combine this combined book with a sword it'll either remove the sweeping edge or just not work if you already have the secondary enchant.

**Comment by TBYT** [comment]
I have a workaround Spigot plugin here just for this, use the latest release https://github.com/TBYT/GeyserParity/releases
Also this issue should stay open as this is not in Geyser yet.

**Comment by onebeastchris** [comment]
Unfortunately, due to certain bedrock limitations, it won't be easily possible to 'enable' this behavior in Geyser. 
Your best bet is probably using a workaround plugin, TBYT's one for example, or try adding the book together with other enchantments.

Bedrock, for some reason, doesn't allow custom enchantments in enchantment tables or anvils - therefore, full 1:1 java enchanting isn't really possible.
Same reason as for why infinity+mending bows can't be made on bedrock even if the server allows it via a plugin - the client partly controls the anvil, it's not fully server side.

**Comment by onebeastchris** [comment]
Okay, that's the behavior that is expected. 
The only reason Sweeping edge shows up at all is because it's shown in the item lore - when combining it, the preview doesn't show sweeping edge, as the preview apparently doesn't have it yet.
But it should - as it did here - show up "again" when combined :)

So yay, that works ~
The only real way we could try and fix this is if Bedrock were to add the enchantment, or if Bedrock would allow anvil behavior modifications

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/2972 closing this in favor of the other post - this boils down to Bedrock having no support for custom enchantments, and us being unable to modify anvil behavior which is controlled client-side.
Thanks anyway for reporting!
