### ISSUE TITLE
xbox and playstation player skins not showing up

### ISSUE THREAD

**Issue by djoveryde** [GeyserMC/Geyser#3704]
### Describe the bug

xbox player skins are not showing, all players have default skins. 
For playstation I've used the geyserskinmanager plugin, but this purely seems to only work for playstation players and the plugin is very outdated.

### To Reproduce

load into a geyser server running on PaperMC from xbox.
Only the default skin shows.

### Expected behaviour

xbox player skins should show up.

### Geyser Version

1.19.4 build 92

### Minecraft: Bedrock Edition Device/Version

xbox 1.19.80

**Comment by onebeastchris** [comment]
Does this issue still occur? Our API that loads skins was briefly down today; the issue might have resolved itself now

**Comment by djoveryde** [comment]
Issue has occured for the past few months, not sure why as have floodgate and geyser installed. Can't figure out why they don't have their own skins

**Comment by lrj1818** [comment]
This Issue Can Be Because You Didnt install Correctly Floodgate Config But You Say All Players? Well if it Also Counts For Java Edition its Because of Floodgate Not Installed Example:In Tutorials You Do Online=false In Server Properties If You Do That Every Skin is Default Like Cracked In order To Solve You Need FloodGate also This Does Fix The Issue And Sometimes Not Depending On  Plugins Or Either Their Wifi And Yours And Server Connection But Mostly Should Fix It Go Check If This Wont Help Resolve Here's A Whole Tutorial For GeyserMc Setup https://www.youtube.com/watch?v=UwTXo-Ig5sc

**Comment by lrj1818** [comment]
This Did Work For Me If Not Idk

**Comment by djoveryde** [comment]
Floodgate is installed, shows skins perfectly fine for Java players, but xbox and playstation players have the vanilla skin. I did work around the playstation players by using geyserskinmanager, but that only fixed playstation and not xbox. I'll double check the setup video incase I did make a mistake

**Comment by lrj1818** [comment]
It May Also Be Wich Skins Their Using Like Wings Or Custom Made Probably Because Some SkinPacks Wont Work Probably This Happened To Me But If They Just Use basic Skins like Birthday Blaze Then idk

**Comment by lrj1818** [comment]
Yea It Might Probably be Wich skin Their Wearing I Tested King Steve Birthday Pack Turned Him Into Normal Default Steve Yea Its Probably Every SkinPack That They Use Because Xbox or Either Playstation users Use Skinpacks i used creeper skin also to test from skinpack

**Comment by lrj1818** [comment]
Try Telling Your Xbox Friends Or Playstation Friends To use Skins without models then it render the skin i tested it for myself heres a screenshot 
![image](https://user-images.githubusercontent.com/77946452/235162025-02b18ecf-23b5-4e4e-bc20-17d092bfb231.png)
If Any Other Skin With Model Gets Used its Default Steve

**Comment by lrj1818** [comment]
It Must Be A Skin That Doesnt Cheat The Model Example:Hat Or Wings Or Other Stuff That May Not be Rendered On Java Edition will result The bedrock client and java client to see the bedrock person has default skin

**Comment by lrj1818** [comment]
Example:
![image](https://user-images.githubusercontent.com/77946452/235166385-95d2055e-fce6-48bb-8942-300e13d18174.png)
![image](https://user-images.githubusercontent.com/77946452/235166592-5ea8665f-9c51-426e-bd79-e73e4aabd553.png)
![image](https://user-images.githubusercontent.com/77946452/235166693-599c21f4-2549-49ac-ba04-40dfcb42104f.png)
If Too Many Models In Your Customization Gets Used It Should Result In Either 2 Options Black Skin Or Default Steve Skin This Is very weird lol why the skin renders is my confusion probably bc i use latest version if you too then should be that

**Comment by lrj1818** [comment]
![image](https://user-images.githubusercontent.com/77946452/235168190-cb394957-a510-4bcd-a6f2-758a079b9f59.png)
![image](https://user-images.githubusercontent.com/77946452/235168354-f92a7534-a50c-440d-b536-5c3e5accdaf8.png)
Skin works because its the new used default skins on new geysermc version but you can see its very buggy so i recommend using none models skins in order to load your skins from playstation xbox or bedrock pc

**Comment by lrj1818** [comment]
There If None Model Skins still load has default steve then your geysermc might have an issue or either outdated geysermc or either floodgate But i hope this should fix your problem.

**Comment by djoveryde** [comment]
none models skins? So I need to get them to do something? Its the latest geyser and floodgate versions installed

**Comment by lrj1818** [comment]
Yep! if You Just Use A Default Skin Without Any Accesorie's Like Models Wings Or hats! it should load! test it if possible

**Comment by lrj1818** [comment]
Like Skinpack blaze or panda without any hats or wings models that break the boundary for java players

**Comment by lrj1818** [comment]
![image](https://user-images.githubusercontent.com/77946452/235171708-f15c7d44-e163-4fb9-aeaa-1980288d924b.png)
Basic Skins Like These Without Models! Should Render 
![image](https://user-images.githubusercontent.com/77946452/235171875-6eb5ac0d-d9b2-4dd5-ac33-93d4342dd6cc.png)
Also This May Be A Delay Bug When Connecting On Geyser That The Bedrock Client See's Himself Has The Previous Skin used But Java Players See The New Skin Should be Fixed By Rejoin!

**Comment by lrj1818** [comment]
![Uploading image.png…]()
If they see them self has previous Skin Just Rejoin And It Should Render Like This ScreenShot

**Comment by onebeastchris** [comment]
Do skins work for you properly now? If they do, this issue could be closed - if they don't show up, please send a new Geyser dump after updating to the latest version.

**Comment by onebeastchris** [comment]
Closing due to no response.

**Comment by onebeastchris** [comment]
Closing due to no response.
