### ISSUE TITLE
Brewing Stands Don’t Work

### ISSUE THREAD

**Issue by RhinoCD** [GeyserMC/Geyser#3790]
### Describe the bug

I can not place anything into a brewing stand to make potions. I can put in the blaze powder and bottles but I cant use nether wart, gunpowder, etc.

### To Reproduce

1. Latest Geyser
2. Join on bedrock
3. Place brewing stand
4. Can’t put items in brewing stand

### Expected behaviour

Being able to brew potions / place items in item slot

### Screenshots / Videos

https://media.discordapp.net/attachments/613168464634576897/1101289367781265438/97539b26-d2c1-4914-ac6c-2231c56e179b_1.mp4

https://media.discordapp.net/attachments/613168464634576897/1110385609282961529/RPReplay_Final1684806821.mov

### Server Version and Plugins

git-Purpur-1961 (MC 1.19.4)

### Geyser Dump

https://dump.geysermc.org/cfWrZRUg1gONYDi72hPIylhNJToNc9UZ

### Geyser Version

2.1.0-SNAPSHOT 

### Minecraft: Bedrock Edition Device/Version

1.19.83

**Comment by onebeastchris** [comment]
Hey there! 
I tried to reproduce the issue with a purpur 1.19.4 server and Geyser Standalone, and i am unable to replicate this issue. I suspect there's a plugin issue going on here, so please try the following steps if the issue is still occurring:

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.
