### ISSUE TITLE
Lava Cauldrons under pointed dripstone renders incorrectly

### ISSUE THREAD

**Issue by payphone101** [GeyserMC/Geyser#3815]
### Describe the bug

Lava inside a cauldron when a dripstone fills it with lava renders incorrectly.
![image](https://github.com/GeyserMC/Geyser/assets/89388404/c276dba4-d741-4036-8349-7b9c2df09092)

### To Reproduce

1. Set up a lava farm using pointed dripstone
2. Wait for the cauldron to fill up or manually fill it with a bucket of lava
3. Lava inside cauldron renders incorrectly (does not occur on bedrock vanilla)

### Expected behaviour

Lava should render like this
![image](https://github.com/GeyserMC/Geyser/assets/89388404/ad686c5b-8222-4211-9f21-6a8b6c5295ec)

### Screenshots / Videos

See description and expected behaviour sections

### Server Version and Plugins

ArmoredElytra, BlueMap, BungeeGuard, Chunky, CoreProtect, DeluxeMenus, DiscordSRV, dynmap, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, Falling, floodgate, LuckPerms, NoEndermanGrief, PlaceholderAPI, Plan, ProtocolLib, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorder

### Geyser Dump

https://dump.geysermc.org/Tl1PDpun4m3KHbt83P2gnrc7slHG70zR

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-246ebdd) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

### Minecraft: Bedrock Edition Device/Version

1.19.81 (Happens on multiple devices)

**Comment by onebeastchris** [comment]
Does the issue go away when updating to 1.20 bedrock?

**Comment by onebeastchris** [comment]
Wasn't able to replicate on 1.20.
My suspicion:
- until 1.20, there was a lava_cauldron block to emit light
- 1.20+ doesnt have that anymore, and uses a different method
Our mappings are now 1.20+, and dont have the lava_cauldron mapping - and since we dont have version-specific block mappings atm, this is likely not easily fixable.

I'll close this then - update to 1.20 to properly see the cauldron in it's lava shimmery glowing glory!
