### ISSUE TITLE
Rendering issues using GSit poses

### ISSUE THREAD

**Issue by Foxvel** [GeyserMC/Geyser#3912]
### Describe the bug

While players are laying using GSit plugin, BE players seeing them clipping into the ground.

### To Reproduce

1. Install GeyserMC and GSit on your server
2. Log in on bedrock and java
3. Use /lay on java
4. Done, bedrock players will see you clipping trough blocks

### Expected behaviour

Bedrock players should see others actually laying.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/130380474/95f549b2-a29d-475e-935c-e6381c2467bd)

### Server Version and Plugins

Current: git-Purpur-2001 (MC: 1.20.1)*
Previous: git-Purpur-1880 (MC: 1.19.3)
* You are running the latest version

### Geyser Dump

https://dump.geysermc.org/jNPVKgURHfXtXAMnpYjvIlTLkjJjZTEK

### Geyser Version

2.1.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.1, Xiaomi Redmi 9a

**Comment by onebeastchris** [comment]
Is this still an issue?

**Comment by Kas-tle** [comment]
Still an issue as of 1.20.71, but also essentially the same cause as https://github.com/GeyserMC/Geyser/issues/2180 which also originally reported issues with `/lay`, but it appears later regressions have broken this again. So will close this as a duplicate given the fix for these will all be similar.
