### ISSUE TITLE
Players can't walk into end gateways when the end gateway isn't in the end

### ISSUE THREAD

**Issue by TheDevMinerTV** [GeyserMC/Geyser#4061]
### Describe the bug

Players can't walk into end gateways when end gateway isn't in the end, like they can in Java Edition.

### To Reproduce

1. Setup a Geyser-enabled server
1. `setblock ~ ~-2 ~ end_gateway` with a Java client on that server in the overworld (you can't `setblock` the end gateway in Bedrock, it just doesn't exist)
2. Try to walk into the end gateway with a Bedrock client on that server
3. You can't walk into the block

### Expected behaviour

You can walk into the block.

### Screenshots / Videos

On our server we're using end gateways as portals between servers as well as some other cool things. This keeps us from having to deal with Nether portal linking issues and end portals being crappy blocks to build with.
[Video showing the repro](http://z.devminer.xyz/u/dMY1WZ.mp4)
![2023-08-17_22 48 13](https://github.com/GeyserMC/Geyser/assets/29845135/90023135-eb4e-4941-98ed-f5edfd812d10)

### Server Version and Plugins

Velocity
```
version
[20:56:44 INFO]: This command does not exist.

plugins
[20:56:52 INFO]: This command does not exist.
```

### Geyser Dump

https://dump.geysermc.org/aXnAdEpP3DbKxSkYukz5evF0DdQ7HqBE

### Geyser Version

https://github.com/GeyserMC/Geyser/commit/9412755

### Minecraft: Bedrock Edition Device/Version

Minecraft: Windows 10 Edition v1.20.15

### Additional Context

I'm not sure if this is something that Geyser can even fix which is why I'm asking here.

**Comment by ZackLackinJava** [comment]
### This is an enhancement /features issue

**Add feature label or related label to guide other helpers**

This is a issue with how clients handle End Gateways, so it's most likely unfixable unless Geyser can fix the problem itself, So there's a high chance it's impossible, Because by DEFAULT, End Gateways are going to be for the end, there's an interference between bedrock client, and the Minecraft server. 

Also please send your plugin list, there's a likelihood that there's a plugin that's interfering with the server's End Gateway event, unless it's a Test Server, Just list here if you can. Thank you!

**Comment by TheDevMinerTV** [comment]
We've figured out that we can walk into the portal anyway and get the event triggered, we've also implemented that players can just sneak + right click on portals to teleport. It's just that the players can't walk into the block.

I guess this is unfixable since it's in Bedrock's code itself. Thank you for commenting though ^^

ℹ️ Closing, can't fix
