### ISSUE TITLE
the chunk not be loading -1.20.1

### ISSUE THREAD

**Issue by nick-1208** [GeyserMC/Geyser#4063]
### Describe the bug

if Bedrock player move some chunk not loading

### To Reproduce

dowload geysermc-1.20.1-spigot

use bedrock login server

run to try loading chunk

and you will see some chunk not be loading

### Expected behaviour

bedrock player can loading all chunk

### Geyser Dump

https://dump.geysermc.org/wCmTku2WHFaqeK7vKJIqDMyQyJILBs1W

### Geyser Version

Geyser-Spigot 1.20.1

### Minecraft: Bedrock Edition Device/Version

1.20.10

**Comment by nick-1208** [comment]
https://discord.gg/F33gFRyfhY my discord server link

**Comment by Konicai** [comment]
Try to reproduce with Geyser's master branch and share a new dump please

**Comment by nick-1208** [comment]
how can i do it?

**Comment by Konicai** [comment]
https://geysermc.org/download

we can't practically offer support on GitHub for forks of Geyser

**Comment by iDarknessSam** [comment]
I'm having the same problem too on my server on Aternos

**Comment by Kas-tle** [comment]
Given this build is now extremely old and the reproduction steps are not clear, this issue is being closed as stale. If this is still a problem, please open a new issue using the latest version and provide specific reproduction steps. Also, given this is Spigot rather than paper, it's likely a duplicate of https://github.com/GeyserMC/Geyser/issues/3809 so please review that before opening another issue.
