### ISSUE TITLE
Issues with /fly after updating Geyser

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#4144]
### Describe the bug

After we updated Geyser, players started experiencing issues with /fly; they can’t use it as anti-cheat systems began to block their flight. This has happened before with Geyser, and the author fixed it; I hasten to report that the problem has occurred again.

### To Reproduce

Install Anti-Cheat Software:
Use any anti-cheat software available, even a basic, vanilla one, to monitor and enforce game rules.

Use the Fly Command:
After enabling the anti-cheat system, enter the "/fly" command to attempt to fly within the game.

Observe the Result:
Finally, observe if the system teleports the player back as it should. If the problem is present, it would not let the player fly, and the user will be teleported back correctly.

Keep in mind, this issue seems to be absent on PCs, so using different devices may give different results.

### Expected behaviour

The player should be able to fly without any issues if they have used the "/fly" command.

### Server Version and Plugins

purpur 1.20.1 | 2062

### Geyser Version

latest 24.09.2023

**Comment by shawn695** [comment]
i have the same issue on my server, bedrock players able to fly when they arn't soppose too i had make a issue as well #4136
like the above stated this had happen before. and it did get fixed. i believe double jump was also a issue back then as well.

**Comment by Caleston** [comment]
Yes this has been an issue again, even though this was fixed a long time ago before.
We are using Themis as well and it flags legitimate flying as horizontal / vertical movement, which then freezes/prevents the player from flying. It was fine before, but for some reason is back again in Geyser.

A temporary fix has been to grant permission for bypassing those checks, but this of course is risky since then Bedrock players could fly with mods.

**Comment by RICE0707** [comment]
I also encountered this vulnerability, Geyser version is Build #1497, bedrock client version is 1.20.31, server version is 1.20.1 (purpur-1.20.1-2022)
