### ISSUE TITLE
Can use placeholder api with jsonui

### ISSUE THREAD

**Issue by Hahaa13** [GeyserMC/Geyser#4255]
### What feature do you want to see added?

Can use PlaceHolderApi with json like display placeholder %player_name% in label of jsonui

### Are there any alternatives?

Not work :))

**Comment by Kas-tle** [comment]
Could you please clarify how this would work? How could we send placeholders that would be accessible via JSON UI? If there's a way to do so in bedrock I'm sure we'd be open to making an API that extension could use, such as one that integrated with PAPI. Just not sure I understand how?

**Comment by Hahaa13** [comment]
Idk :))

**Comment by Tydium** [comment]
This issue is unnecessary given the fact that JSON UI already works with all the elements on the screen. My point being is that if you use placeholder API on a scoreboard it should just automatically work and you can modify the visuals using JSON UI. Therefore this is technically already a "feature" by nature.
