### ISSUE TITLE
Support for Fabric 1.20.1

### ISSUE THREAD

**Issue by JefferyPlayz** [GeyserMC/Geyser#4316]
### What feature do you want to see added?

Please add support for Fabric 1.20.1 and even maybe lower versions. Most other mods not supporting 1.20.2 yet, therefore many modded servers are unable to use Geyser.

### Are there any alternatives?

Every time I try there is always an error in my console that says Geyser and Floodgate do not support 1.20.1 and need a Minecraft version higher than 1.20.2 to work.

This is really annoying and there doesn't seem to be any alternative mods that do the same thing. Please add this 🙏.

**Comment by Konicai** [comment]
So here's the thing:
1. Geyser always emulates the latest Java Edition client (1.20.2 currently)
2. ViaFabric only ever supports the last minor version of a major minecraft version (eg 1.18.2, 1.19.4, 1.20.2)

This means that even if Geyser supported Fabric 1.20.1, you wouldn't be able to actually join because you wouldn't be able to install ViaFabric.

If you need to run an older Fabric server then I suggest using Geyser-Standalone until you can update it.
