### ISSUE TITLE
Items on head?

### ISSUE THREAD

**Issue by Williambriggs1** [GeyserMC/Geyser#4432]
### Describe the bug

On the velocity version I able to

on java: run /hat with a log in your hand, it puts it on your head
on bedrock: they see the log on the players head?

But i am now running a server with the spigot version and bedrock cant see the log? 

### To Reproduce

Pretty self explainatory,
1. install geyser-spigot
2. java does /hat
3. bedrock doesn't see the item java just put on they're head

### Expected behaviour

Bedrock can see the item on the head

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/53185925/9a0f1a62-25a4-4231-bb41-3cf1060bdaf7)
Java perspective ^

![image](https://github.com/GeyserMC/Geyser/assets/53185925/04fad560-5a73-4574-a0c9-8a0aa7031703)
^ Bedrock

### Geyser Dump

https://dump.geysermc.org/afcZDA02rT1jrqMNupLlNmzW4gq634SB

### Geyser Version

2.2.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.60 Microsoft

**Comment by onebeastchris** [comment]
From discord:

[..] Bedrock doesn't render almost any items on the head. If you only need to render specific items you could feasibly make attachables... but of course to do every item that would be hundreds so that's why we don't do any in GeyserOptionalPack


In short, you can add an attachable for the item that you need to be shown on the skull, but ultimately this isn't something that's feasible to fix in Geyser.
