### ISSUE TITLE
Could geyser support custom sound?

### ISSUE THREAD

**Issue by CatTimothy** [GeyserMC/Geyser#4465]
### What feature do you want to see added?

Setup custom sound like custom item with bedrock resource pack.

let it can setup like this
https://wiki.geysermc.org/geyser/custom-items/

### Are there any alternatives?

no

**Comment by onebeastchris** [comment]
Custom sounds are already possible, and only require setting up a Bedrock resource pack - no mappings required.

See https://wiki.bedrock.dev/concepts/sounds.html for more information. The only important thing - you should register custom sounds under a custom namespace, e.g. `test:my_sound`, instead of e.g. `minecraft:my_sound` or even no namespace.
