### ISSUE TITLE
Protocol underlying with overhead

### ISSUE THREAD

**Issue by PedroMPagani** [GeyserMC/Geyser#4518]
### What feature do you want to see added?

I think geyser should adopt most of all of the sendPacket methods to be immediate,
the sendPacket( method runs a batching pool only on the client tick, if you have a login, or such massive login rates from a lot of players this will shoot the CPU high up, and it can cause kicks because of this too. (Not to consider the excessive memory usage caused by this extremely fast because of the high allocation rate). 

### Are there any alternatives?

the method sendPacketImmediately does not run this queue, which will reduce the memory usage overall from geyser possibly too, as well as it should improve the stability of it,

I would like to test this myself first, so I'll do this on DonutSMP and we see if this is a big improvement.

**Comment by Redned235** [comment]
This batching is a very important step in the protocol. Packets are sent out in batches every tick, and realistically for each client, this will not have a major effect on memory usage for Geyser. The Bedrock protocol natively supports batching and this will adversely affect both clients and the server by disabling it. Sending the packets out immediately will increase CPU noticeably and will reduce the efficiency of compression, since each individual buffer will be far smaller.

With a higher number of clients joining at once, it should be expected for resource usage across the board to jump before leveling out. If you are noticing high amounts of packets being left in a queue causing memory usage to be abnormally high, it's best to capture a heap dump and investigate further from there.

With that being said, unfortunately this is not something we're interested in pursuing. Thanks for the suggestion though!
