### ISSUE TITLE
Combat translation

### ISSUE THREAD

**Issue by ThrowerWay** [GeyserMC/Geyser#4640]
### What feature do you want to see added?

I'd like a way to translate noob spam click pvp to 1.9 timed hits. More akin to what bedrock is designed for.

### Are there any alternatives?

Letting bedrockers pvp wrongly.

**Comment by onebeastchris** [comment]
You can use a third-party plugin like OldCombatMechanics for that. Geyser emulates the latest Minecraft Java edition client, and e.g. pvp behavior is set by the server.

**Comment by onebeastchris** [comment]
Spam clicking with Geyser on a 1.20 server will do exactly nothing - since the combat is the same Java edition one. Axes deal more damage, there are cooldowns, etc. 
It's outside the scope (and, with Geyser not always being on the same server, downright impossible) to modify combat mechanics for Bedrock players only. Hence, you have the option to either explain to your players that they'll have to use Java mechanics - or you could switch the whole server over to 1.8 combat with the aforementioned plugin (which would work similar to Bedrock's current combat system).
Geysers goal is to emulate a Java client as closely as possible, not to bring Bedrock features to a Java server.
