### ISSUE TITLE
Very Confused. Get outdated message.

### ISSUE THREAD

**Issue by guhg** [GeyserMC/Geyser#4643]
### Describe the bug

I'm super confused, IDK if this is a bug or if I'm doing something wrong. I downloaded the LATEST geyser spigot.jar from the geyser mc website. I then put it into the plugins folder of my g portal server. Now, anything I try to join Bedrock in 1.20.80, it says the the geyser plugin is outdated. But, I thought I downloaded the latest! I don't understand.

### To Reproduce

Idk

### Expected behaviour

![Screenshot_20240506_110624_Minecraft](https://github.com/GeyserMC/Geyser/assets/41343639/2aed3ba9-3696-41a5-bc5f-6c255ac9bcef)

### Geyser Version

Latest from website 

### Minecraft: Bedrock Edition Device/Version

1.20.81/1.20.80

**Comment by onebeastchris** [comment]
One of two things are happening here:
- You're not updating the plugin correctly (e.g. incorrect plugin folder, uploading the old file instead of the new one, etc)
or 
- your server hosting provider/some setup is replacing the jar, e.g. a faulty auto-updater.

Please try the following:
- stop the server
- fully delete the `Geyser-Spigot.jar` file from your `/plugins/` folder.
- remove all `Geyser-Spigot.jar`'s from your downloads folder
- download the latest build from https://geysermc.org/download
- upload that jar to the `plugins` folder 
- start the server again.

If you're still seeing this error message after following these steps, contact your host and ask them if they're changing the Geyser jar - this could be an issue on their side.
