### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by prodrias** [GeyserMC/Geyser#4671]
### Describe the bug

im stuck in a Unable to connect to world loop ever since i updated to the latest, config was left untouched

### To Reproduce

update the plugin, and restart the server

### Expected behaviour

no errors.

### Server Version and Plugins

Paper version 1.20.6-79-master@f175193
Floodgate 2.2.3-SNAPSHOT (b103-f8c8418) (branch: master)

### Geyser Dump

https://dump.geysermc.org/yCaZXGpjnQryLf27VkSLrVRUcoExXHXD

### Geyser Version

Geyser-Spigot v2.3.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.81 iPhone

**Comment by onebeastchris** [comment]
Please join our discord server for help with "Unable to connect" issues. If you are not seeing any further errors, this is likely caused by a firewall, which might have changed.

The only networking change that did happen between 1.20.80 support and now was the addition of an additional security layer (raknet cookies), which currently clashes with the OVH's (a server hosting provider) game firewall when that's set to `minecraftPocketEdition`. See here for more details & fix: https://wiki.geysermc.org/geyser/port-forwarding/#ovh-and-soyoustart

If you are unsure what to do with this information, or are not using OVH but some different server hosting provider - please join our [discord server](https://discord.com/invite/geysermc) and we'll be able to help there. Thanks!

**Comment by prodrias** [comment]
yea but i joined the discord yesterday, asked for help since yesterday and still havent gotten an answer which is why im here on the github.
