### ISSUE TITLE
Add support for 1.20.4

### ISSUE THREAD

**Issue by RedCoder09** [GeyserMC/Geyser#4698]
### What feature do you want to see added?

My (Quilt) server is on 1.20.4, but the latest versions of Geyser and Floodgate won't work because they're built for 1.20.5 and higher. I tried ViaFabric, but it doesn't fix the server rejecting the mods because the server isn't on 1.20.5. How could I fix this? Do you have to add support for 1.20.4 altogether?

### Are there any alternatives?

ViaVersion

**Comment by onebeastchris** [comment]
For the time being, you could download an old 1.20.4 Geyser-Fabric build from modrinth.

Generally speaking, we do not plan to support older versions on modded platforms due to the immense added workload. Hence why we (currently) only support the latest version, currently being 1.20.6.

However, this doesn't mean that you can't use Geyser on an older server. For example, you can use the Geyser plugin on a Viaproxy instance and then connect to an older server - this would work as Viaproxy is doing the 1.20.6 -> 1.20.4 transaction.

For more information on how to use & set up Geyser, please see our setup guide; it covers that as well: http://wiki.geysermc.org/geyser/setup/
