### ISSUE TITLE
Badrock player taking to long to join but not joing

### ISSUE THREAD

**Issue by samir717le** [GeyserMC/Geyser#4727]
### Describe the bug

Fix it

### To Reproduce

Don't known

### Expected behaviour

Click and join server in a second 

### Geyser Dump

https://dump.geysermc.org/sYdpmZdLhhyT4C7IkvueXNw4z17VL3Zy

### Geyser Version

Latest

**Comment by onebeastchris** [comment]
This sounds like a configuration issue.

Please see our documentation for how to setup and configure Geyser:
https://wiki.geysermc.org/geyser/setup/
https://wiki.geysermc.org/geyser/common-issues/

For further setup help, please use the discord server for support. 
Closing this issue due to little to no information provided, and because support requests are handled on our discord instead.
