### ISSUE TITLE
Nothing is synchronized with java and bedrock.

### ISSUE THREAD

**Issue by chebupelka10** [GeyserMC/Geyser#4810]
### Describe the bug

Nothing is synchronized with java and bedrock. That is, I log in with the same nicknames and still I spawn in different places. I can see myself with java as with bedrock and vice versa. This is dump https://dump.geysermc.org/6JbZI45NeebbJdoaiNOZeNpiYxF7dqOv

### To Reproduce

1. I installed geysermc to my server and set prefix +.
2. my bedrock account kicked out of the game with error invalid username.
3. i set prefix to nothing
4. I have two chepuxcats in my server

### Expected behaviour

Nothing is synchronized with java and bedrock. That is, I log in with the same nicknames and still I spawn in different places. I can see myself with java as with bedrock and vice versa. This is dump https://dump.geysermc.org/6JbZI45NeebbJdoaiNOZeNpiYxF7dqOv

### Screenshots / Videos

https://prnt.sc/lvPlz1DKV-Cj

### Server Version and Plugins

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version. https://dump.geysermc.org/6JbZI45NeebbJdoaiNOZeNpiYxF7dqOv

### Geyser Dump

https://dump.geysermc.org/6JbZI45NeebbJdoaiNOZeNpiYxF7dqOv

### Geyser Version

2.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21.1, windows and android

**Comment by onebeastchris** [comment]
Disabling the prefix will cause username clashes, that's why it exists. However, having the same name will not result in the same account, as the UUID's are different.
Floodgate has an account linking functionality that you should use. However, note that global linking only works on online mode servers. Offline mode servers are not supported.

See here for more info on account linking: https://wiki.geysermc.org/floodgate/linking/
