### ISSUE TITLE
read timed out

### ISSUE THREAD

**Issue by Cacto890** [GeyserMC/Geyser#4879]
### Describe the bug

When trying to connect from bedrock i can reach all the servers, but the server named "nokep" in my velocity.toml. i saw some github issues related to this  but i couldn't fix it. Tried to install ViaVersion on all not proxy (so backend) servers and putting floodgate in every server with key.pem and config. Idk why it happened. It came out of nowhere! Please Help ASAP!
oh and i have modern forwarding setup

Thank U: Cacto

### To Reproduce

1. Add server with Velocity proxy infront of it
2. Attempt to connect
3. Get kicked

### Expected behaviour

Bedrock users connect to backend server trough a velocity proxy

### Server Version and Plugins

Version : 1.20.4
Plugins: ViaVersion (Only Backends), GeyserMC, floodgate (Backend and proxy) EssentialsX, LuckPerms

### Geyser Dump

https://dump.geysermc.org/3RCI30oNEfSBMglfXXGjVKJUmjt122jd

### Geyser Version

2.2.3 SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21 Android, all bedrock devices

**Comment by onebeastchris** [comment]
"Read timed out" just indicates that the Java server did not send a packet for over 30 seconds. This is not a Geyser issue, but instead often caused by incorrect configuration/plugin errors.

See whether:
- a 1.21 Java client is able to connect to said server
- try moving ViaVersion (as they recommend) to the backend servers instead of the proxy
- Test it this occurs without other plugins.

Further, offline mode servers are not supported.

**Comment by Cacto890** [comment]
It is because it only accurs on bedrock
