### ISSUE TITLE
what is a ipv6 address format?

### ISSUE THREAD

**Issue by spagu** [GeyserMC/Geyser#4888]
### What feature do you want to see added?

what is a proper ipv6 address to be configured?

```
[06:33:10 ERROR] Failed to start Geyser on 0:0:0:0:0:0:0:0:19132
[06:33:10 INFO] Suggestion: try setting `address` under `bedrock` in the Geyser config back to 0.0.0.0
[06:33:10 INFO] Then, restart this server.
```

```yaml
bedrock:
  # The IP address that will listen for connections.
  # Generally, you should only uncomment and change this if you w
  address: 2a01:4f6:156:1181::182
  #address: 10.132.132.132
  #address: 0:0:0:0:0:0:0:0
  # The port that will listen for connections
```

currently any format just give error message.

### Are there any alternatives?

?

**Comment by onebeastchris** [comment]
`0:0:0:0:0:0:0:0` (or, wildcards such as `::`), or the full ipv6 as the "bedrock address" should work fine. Note that you usually do not need to change the default. In your case, it seems like the root cause is not actually the way you wrote the ip in the config - check your full logs to see why it failed to start (the stacktrace above the "failed to start"). It could be the "Address in use" error, or any other - for troubleshooting, please visit our documentation on https://geysermc.org/wiki/geyser/ or join our discord server and ask for help there.
