### ISSUE TITLE
I can't access the server with the error message: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by HaiYTB** [GeyserMC/Geyser#4889]
### Describe the bug

When I log into the server at night, it's like this (my network service provider is having a cable break).

### To Reproduce

Log: https://mclo.gs/dLNR6Pw
Here are the plugins 👇
![Screenshot_2024-07-23-21-38-58-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/3662f24a-474b-4cf1-b8a5-cd156420f711)

### Expected behaviour

Message error in game: 
![Uploading Screenshot_2024-07-23-21-37-15-06_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

### Geyser Dump

https://dump.geysermc.org/0RSCYIgPRgNutHC53HCOlcXVEdnHoUHB

### Geyser Version

2.4.0-b617 (git-master-1dd9ba3) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

### Minecraft: Bedrock Edition Device/Version

1.20.81

**Comment by HaiYTB** [comment]
P/S: Or the error message will be: Connection Closed and no error message in the console :v

![Screenshot_2024-07-23-21-54-00-90_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/user-attachments/assets/3d5a5432-9ca5-44ea-8970-b2ceb259bfac)

**Comment by onebeastchris** [comment]
![image](https://github.com/user-attachments/assets/edaaca02-3e80-4eb9-860b-1915a3b58ab3)
This does not look like "no error message" to me. The server could not spawn the player, which is why the connection is terminated - this is not a Geyser issue, and instead caused by something on the server. I'd recommend asking in the paper discord for help with this.
