### ISSUE TITLE
Mcxboxbroadcast

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [GeyserMC/Geyser#4967]
### Describe the bug

This is broken may you fix it
It says unable to connect to world

### To Reproduce

1. install it 2. Use it 3. Link a acc and try to join from it

### Expected behaviour

It will say locating server and let me join

### Server Version and Plugins

1.21.1

### Geyser Version

Build #648 bungeecord

### Minecraft: Bedrock Edition Device/Version

1.21.20 Android now.gg

**Comment by lolwhatdidigetbanned** [comment]
The 1.21.20 connection is the  cause not the plugins it worked with my bungee plugins and spigot

**Comment by Camotoy** [comment]
We are aware this plugin is broken. We believe Mojang made a change that requires an IMMENSE rewrite of both the plugin and Geyser for MCXB to become viable again. Making more issues will not get the problem solved faster because there is no easy fix here - for now, you need to use BedrockConnect or BedrockTogether for consoles to join your server.

**Comment by lolwhatdidigetbanned** [comment]
> We are aware this plugin is broken. We believe Mojang made a change that requires an IMMENSE rewrite of both the plugin and Geyser for MCXB to become viable again. Making more issues will not get the problem solved faster because there is no easy fix here - for now, you need to use BedrockConnect or BedrockTogether for consoles to join your server.

Some of my members require mcxboxbroadcast to join my server but any other plugin that works not dns or bedrock together and this affected the robotgc community made bot and how did Mojang break it, now I’m going to put. A middle sign in front of Microsoft hq
