### ISSUE TITLE
Crafting Tables not working on legacy versions (Java Edition 1.11 or lower) of the game

### ISSUE THREAD

**Issue by nutellamanxd** [GeyserMC/Geyser#511]
**Describe the bug**
Unable to craft anything in a regular crafting table

**To Reproduce**
Try to craft something

**Expected behavior**
My furnace to appear in the crafting

**Screenshots / Videos**
https://youtu.be/XnQY6U60--c

**Server Version**

PaperSpigot 1.8.8

**Geyser Version**
Bungeecord Build 128

**Minecraft: Bedrock Edition Version**
Latest

**Additional Context**
None

**Comment by Chew** [comment]
Does it still happen on the latest build?

**Comment by DoctorMacc** [comment]
Likely that it does - we haven't updated crafting support. This is something specific to the way that 1.8 works.

**Comment by Chew** [comment]
Hmm, would whatever protocol hack they're using be causing this? Or is it explicitly Geyser

**Comment by Heath123** [comment]
Is this likely to be fixed in the 1.16 inventory rewrite?

**Comment by RednedEpic** [comment]
What is your server version? If you're running 1.8, crafting is broken in that version with Geyser.

**Comment by DoctorMacc** [comment]
Crafting is broken between versions 1.8 and 1.11.

**Comment by DoctorMacc** [comment]
My current theory here is that we need to send a list of every crafting recipe available in order for recipes to show up. Java Edition 1.12 or later does this for us, but we're on our own for earlier versions. So it's possible to support these versions but it would require manually creating every available recipe. Therefore, don't expect this to get added for a while.

**Comment by Chew** [comment]
How would this work for custom recipes?

**Comment by DoctorMacc** [comment]
I don't believe custom recipes were a thing pre-1.11. Please correct me if I am wrong.

**Comment by KaiKikuchi** [comment]
Hello! I was wondering if anyone had any tip for a temporary server-side fix of this bug.

Although I am a programmer, I am not exactly sure what is causing this bug. Java Edition 1.16 players can craft items without any issue, so I am unsure what packet the server is not sending to Bedrock Edition clients. Maybe there is one or more packets that the server could send to Bedrock Edition clients that will unlock all recipes. I'd like to make such a server-side plugin that will just do that when a Bedrock Edition player joins the server.

There are a lot of players that don't have access to a PC but they have a console and I'd like to let them play. 

I mostly use 1.8 PaperSpigot servers with the latest snapshot version of ViaVersion. I can't really update my servers to the latest Minecraft version because most of the players of my server are into 1.8 PvP.

I started using standalone Geyser + Floodgate on my servers back in early December 2020. I really like it and I am recommending it to anyone that has a 1.16 server and wants to add Bedrock Edition support! Thank you for all the hard work you put on it!

**Comment by Camotoy** [comment]
> I can't really update my servers to the latest Minecraft version because most of the players of my server are into 1.8 PvP.

I would recommend you look into something like https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/.

The `server-inventory` Geyser branch is now in testing and has support for legacy crafting.

**Comment by KaiKikuchi** [comment]
> Otherwise, the `server-inventory` Geyser branch is now in testing and has support for legacy crafting.

Thank you for the quick response! I'm going to compile that and try it out. Should I make a new issue if I find any issue with that one?

**Comment by Camotoy** [comment]
No need to compile it as it is available on our CI! https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/server-inventory/

Yes, please report any issues as a new issue here.

**Comment by KaiKikuchi** [comment]
> No need to compile it as it is available on our CI! https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/server-inventory/

I ended up compiling it and testing it before reading this comment.

It looks like it works fine! Thanks!

**Comment by MrZomka** [comment]
> 
> 
> Hello! I was wondering if anyone had any tip for a temporary server-side fix of this bug.
> 
> Although I am a programmer, I am not exactly sure what is causing this bug. Java Edition 1.16 players can craft items without any issue, so I am unsure what packet the server is not sending to Bedrock Edition clients. Maybe there is one or more packets that the server could send to Bedrock Edition clients that will unlock all recipes. I'd like to make such a server-side plugin that will just do that when a Bedrock Edition player joins the server.
> 
> There are a lot of players that don't have access to a PC but they have a console and I'd like to let them play.
> 
> I mostly use 1.8 PaperSpigot servers with the latest snapshot version of ViaVersion. I can't really update my servers to the latest Minecraft version because most of the players of my server are into 1.8 PvP.
> 
> I started using standalone Geyser + Floodgate on my servers back in early December 2020. I really like it and I am recommending it to anyone that has a 1.16 server and wants to add Bedrock Edition support! Thank you for all the hard work you put on it!

Please move to at least 1.12 (or even better 1.16.5) as soon as possible.
