### ISSUE TITLE
chests animation is broken

### ISSUE THREAD

**Issue by MirMiksan** [GeyserMC/Geyser#5148]
### Describe the bug

after updating to the latest version of geyser animations when opening an ender chest, chest, chest traps disappeared

### To Reproduce

1 Update to the latest version of the geyser
2 Open the chest or ask to open it from another account
3 There is no opening animation

### Expected behaviour

That the animation will work as before, when animating the opening on Java, the animation will also be played on the geyser

### Geyser Version

2.5.0-SNAPSHOT (git-DEV-cde0cae)

**Comment by benshan36** [comment]
I couldn't replicate the issue, try seeing if updating geyser fixes it. You're using a dev version

**Comment by onebeastchris** [comment]
Closing - i'm also unable to replicate this issue. For future issue/bug reports, please fill out the full issue report - a Geyser dump would've shown what Geyser platform/server version this is occurring on, alongside other important metrics.

If this issue is still occurring, please open a new, fully filled out issue. Thanks!
