### ISSUE TITLE
Allow old Bedrock player to come in

### ISSUE THREAD

**Issue by Jam-04** [GeyserMC/Geyser#5249]
### What feature do you want to see added?

My server has many different kinds of player, but some of their devices are no supported to update their game. They can only play 1.20 or even older, but my server is 1.21, and some of the players use 1.21.51 to came in! So I would love to ask whether you could add this function into Geyser, making this useful plugin better.

### Are there any alternatives?

ViaProxy, but it cannot do what I say. It can only support the newest Bedrock Edition

**Comment by Chew** [comment]
Due to the technical limitations and workload to support each Bedrock version, we can only support the latest Bedrock versions. You could use an older version of Geyser to support them, but it obviously would not allow newer Bedrock versions to join, and you would be missing out on the latest features and bug fixes. Unfortunately, we have no plans to support this. Thank you for your suggestion, though!
