### ISSUE TITLE
Aiming a bow puts player in swimming animation

### ISSUE THREAD

**Issue by ShyloFluff** [GeyserMC/Geyser#563]
When playing Turf Wars on Mineplex, my screen kept on lowering to the ground every time I aimed a bow it. It effects all players on screen aiming a bow as well

**Comment by rtm516** [comment]
> When playing Turf Wars on Mineplex, my screen kept on lowering to the ground every time I aimed a bow it. It effects all players on screen aiming a bow as well

Please follow the bug report template

**Comment by RednedEpic** [comment]
Seems to be specific to Mineplex itself. We've had various issues with them sending invalid packet data to Geyser and causing some problems like this (just joining alone caused my console to spam with invalid entity data because they send the wrong data here). Closing for now as this is nothing we can really fix.

**Comment by Heath123** [comment]
If it works on vanilla it should work on Geyser though

**Comment by lukeeey** [comment]
It can only mean that the vanilla client has support for whatever data they’re sending so we should look into implementing that too.
