### ISSUE TITLE
Config reset

### ISSUE THREAD

**Issue by kirjorjos** [GeyserMC/Geyser#581]
Config "resets" to something that should not be generated on restart
`# --------------------------------
# Geyser Configuration File
metrics:
  uuid: aa2b69ea-66b9-4ba2-b58e-6af068c4f2a7
remote:
  port: 25585
bedrock: {}
`

**To Reproduce**
Install [these](https://cdn.discordapp.com/attachments/613168464634576897/711394230450257921/unknown.png) plugins on paper 1.15.2
configure geyser with floodgate enabled the proper way
restart the server or reload geyser using /geyser reload

**Expected behavior**
To not reset the config on restart

**Server Version**
Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-b4ecb88)

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Additional Context**
![image](https://user-images.githubusercontent.com/35607697/82134185-272e8b00-97c3-11ea-91f0-89a35d4472c0.png)

**Comment by rtm516** [comment]
I suspect this is due to the automatic  IP and port detection done, as it tries to update the file afterwards.

**Comment by DoctorMacc** [comment]
Does this happen without the plugins?

**Comment by kirjorjos** [comment]
Yes, it still happens with no plugins.

**Comment by DoctorMacc** [comment]
Odd - I'm not able to replicate it on Paper 273 with Essentials, Floodgate, Skript, Floodgate-Skript and WorldEdit. If anyone else can replicate this, please fill in details on how to replicate.

**Comment by kirjorjos** [comment]
I probably should have put this under additional context, but I'm using pebblehost's 4 GB plan.

**Comment by RednedEpic** [comment]
Before you save and restart the server, can you send us what your config looks at that time?

**Comment by kirjorjos** [comment]
# --------------------------------
# Geyser Configuration File
bedrock:
  address: 0.0.0.0
  port: 25585
  motd1: GeyserMC
  motd2: \u00A76Metaverse SMP: \u00A7bThe only server you\'ll ever need!
remote:
  address: 149.56.155.18
  port: 25585
  auth-type: floodgate
floodgate-key-file: public-key.pem
ping-passthrough: false
max-players: 100
debug-mode: false
general-thread-pool: 32
allow-third-party-capes: true
default-locale: en_us
cache-chunks: false
metrics:
  enabled: true
  uuid: 1cf5d74f-3526-4920-9a30-6d064820fc3e

**Comment by rtm516** [comment]
Can you wrap that in \`\`\` as seen [here](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by 12emin34** [comment]
I encountered this bug too, here's some info:

**Describe the bug**

When doing `/geyser reload` the config.yml file resets to the default config.

**To Reproduce**

Install Geyser-Bukkit

Start the server

Open config.yml and make some changes

Do `/geyser reload`

Open config.yml again, it will be reset.

**Expected behavior**

Geyser should load the new settings from config.yml

**Screenshots / Videos**

Not applicable

**Server Version**

git-Paper-309 (MC: 1.15.2)

**Geyser Version**

Geyser-Bukkit version 1.0-SNAPSHOT (build 173 - master branch)
Not using Floodgate

**Minecraft: Bedrock Edition Version**

Not applicable

**Additional Context**

Java version: Java 8 (OpenJ9 0.20.0)
Machine is running Linux 4.15.0-58
Plugins:
AntiBotDeluxe, AuctionHouse, BossBarPlus, ChestShop, ChestShop-towny, ClearLag, CoreProtect, CratesPlus, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, ExploitFixer, FastAsyncWorldEdit, Geyser-Bukkit, GriefPrevention, HamsterAPI, HubBasics, IridiumSkyblock, Jobs, LastMinerStanding, LoginSecurity, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, PermissionsEx, PluginConstructorAPI, ProtocolLib, ProtocolSupport, ProtocolSupportLegacySupport, ProtocolSupportStuff, QualityArmory, QualityArmoryBackpacks, Reserve, SignShop, SkinsRestorer, Space, Spleef, SuperVanish, TitleManager, Towny, TownyNameUpdater, Vault, ViaVersion, VoidGenerator, Votifier, VotingPlugin, VoxelSniper, WorldEdit, WorldGuard, WorldGuard-Towny

**Comment by DoctorMacc** [comment]
Could you try #653 and see if the problem is solved?

**Comment by 12emin34** [comment]
I have tried the pull and it seems to be fixed.

**Comment by DoctorMacc** [comment]
Likely fixed with #653.
